
## This file creates the data for the mark-resight multi-event model with both sexes, run in SSL_CJS.Rmd. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set up}

library(here) #v1.0.1
library(dplyr) #v1.0.5
library(lubridate) #v1.7.20
library(reshape2) #v1.4.4
library(Hmisc) #v4.5-0; %nin%

```

```{r create CH}

filter_yr <- 1989

# data_raw <- read.csv(here::here('data', "2025_CCEP_Zc_CH.csv"), 
#                   header = T, stringsAsFactors = F) %>%
#   filter(cohort > filter_yr)

#google drive June 2026 from S. Melin
data_raw <- read.csv(here::here('data', 'CSL_San Miguel Island_Capture History CH_20260622.csv'),
                     header = T, stringsAsFactors = F) %>%
 filter(cohort > filter_yr)

ch_dat_f <- data_raw %>%
  dplyr::select(brand:X25) %>%
  filter(adjsex != 'M')

ch_dat_m <- data_raw %>%
  dplyr::select(brand:X25) %>%
  filter(adjsex == 'M')

#this info is only in the original MR data
# areas_f <- data_raw %>%
#   filter(adjsex != 'M') %>%
#   dplyr::select(brand, cohort, area11991:area22024)
# 
# areas_m <- data_raw %>%
#   filter(sex == 'M') %>%
#   dplyr::select(brand, cohort, area11991:area22024)

# repro_f <- data_raw %>%
#   filter(sex != 'M') %>%
#   dplyr::select(brand, cohort, repro1993:repro2024)
# 
# repro_m <- data_raw %>%
#   filter(sex == 'M') %>%
#   dplyr::select(brand, cohort, repro1993:repro2024)

##melt to get into ages/states instead of just 1's and 0's
res_long <- ch_dat_f %>%
  dplyr::select(-c(sex)) %>%
  reshape2::melt(id.vars = c('brand', 'cohort', 'adjsex', 'weight')) %>%
  transform(variable = gsub('X', '', variable)) %>%
  transform(variable = ifelse(variable %in% c('87', '88', '89', '90', '91', '92', 
                                              '93', '94', '95', '96', '97', '98', '99'), 
                              paste0('19', variable), paste0('20', variable))) %>%
  transform(variable = as.numeric(variable)) %>%
  transform(years_old = variable-cohort) %>%
  filter(years_old >= 0) %>%
  #add 1 so pup is z == 1
  transform(ch = years_old+1) %>%
  #plus group <= 17, says 18 since added one in line above
  transform(ch_cat = ifelse(ch >= 18, 18, ch)) %>%
  #now add back the not detected using "value" 0 or 1 from raw dat
  transform(ch_cat = ifelse(value == 1, ch_cat, NA)) %>%
  #remove intermediate columns and recast using variable/year
  dplyr::select(-c(years_old, value, ch)) 

#fill grid for 2020 surveys that are missing
fill_grid <- expand.grid(brand = unique(res_long$brand),
                         variable = c((filter_yr+1):2024))

# test <- res_long %>% #filter(brand == '9102') %>% 
#   merge(fill_grid, by = c('brand', 'variable'), all = T) 

res_dat_f <- res_long %>% #filter(brand == '9102') %>% 
  merge(fill_grid, by = c('brand', 'variable'), all = T) %>% 
  reshape2::dcast(brand + cohort + adjsex + weight ~ variable, value.var = 'ch_cat', fill = 19) %>%
  arrange(cohort, brand) %>%
  #filters out awkward blanks in wt, cohort, sex when expanded grid for 2020
  filter(!is.na(cohort))

res_long_m <- ch_dat_m %>%
  dplyr::select(-c(sex)) %>%
  reshape2::melt(id.vars = c('brand', 'cohort', 'adjsex', 'weight')) %>%
  transform(variable = gsub('X', '', variable)) %>%
  transform(variable = ifelse(variable %in% c('87', '88', '89', '90', '91', '92', 
                                              '93', '94', '95', '96', '97', '98', '99'), 
                              paste0('19', variable), paste0('20', variable))) %>%
  transform(variable = as.numeric(variable)) %>%
  transform(years_old = variable-cohort) %>%
  filter(years_old >= 0) %>%
  #add 1 so pup is z == 1
  transform(ch = years_old+1) %>%
  #plus group <= 17, says 18 since added one in line above
  transform(ch_cat = ifelse(ch >= 18, 18, ch)) %>%
  #now add back the not detected using "value" 0 or 1 from raw dat
  transform(ch_cat = ifelse(value == 1, ch_cat, NA)) %>%
  #remove intermediate columns and recast using variable/year
  dplyr::select(-c(years_old, value, ch)) 

fill_grid <- expand.grid(brand = unique(res_long_m$brand),
                         variable = c((filter_yr+1):2024))


res_dat_m <- res_long_m %>% 
  merge(fill_grid, by = c('brand', 'variable'), all = T) %>%
  reshape2::dcast(brand + cohort + adjsex + weight ~ variable, value.var = 'ch_cat', fill = 19) %>%
  arrange(cohort, brand) %>%
  #filters out awkward blanks in wt, cohort, sex when expanded grid for 2020
  filter(!is.na(cohort))


```

```{r known dead}



```


```{r write csvs}

## ALL INDIVIDUALS

write.csv(res_dat_f,
          file = here::here('data', 'res_dat_f_20260623.csv'), row.names = F)

write.csv(res_dat_m,
          file = here::here('data', 'res_dat_m_20260623.csv'), row.names = F)



```

```{r strandings for lepto/DA cases}

library(lubridate)
library(stringr)
library(readr)
library(ggplot2)

strand_dat <- read.csv(here('data', 'CSL Strandings 2014-2025.csv'))

dat <- strand_dat %>%
  transform(Date.of.Examination = ifelse(Date.of.Examination == '', 
                                         Died.Date, Date.of.Examination)) %>%
  transform(date = mdy(Date.of.Examination)) %>%
  transform(year = year(date)) %>%
  select(year, Cause.of.Death, Other.Findings...Describe, 
         Condition.Comments, Died.Comments, Additional.Remarks,
         Rehab.Additional.Remarks) 

colnames(dat) <- c('year', 'com1', 'com2', 'com3', 'com4', 'com5', 'com6')

dat <- dat %>%
  mutate(lep_yes = if_any(c(com1, com2, com3, com4, com5, 
                            com6), ~ str_detect(.x, 'lep'))) %>%
  mutate(DA_yes = if_any(c(com1, com2, com3, com4, com5, 
                            com6), ~ str_detect(.x, 'domoic'))) 

dat_yr <- dat %>%
  filter(!is.na(year)) %>%
  filter(year > 2013) %>%
  group_by(year) %>%
  dplyr::summarize(lep = mean(lep_yes),
                   DA = mean(DA_yes))

da_early <- read_tsv(here('data', 'DA.txt'))

lep_early <- read_tsv(here('data', 'lepto.txt'))

all_yrs <- dat_yr %>%
  melt(id.vars = 'year') %>%
  transform(variable = factor(variable, levels = c('lep', 'DA'),
                              labels = c('Lepto', 'DA')))

ggplot(all_yrs, aes(x = year, y = value, color = variable)) +
  geom_point() +
  geom_line() +
  xlab('') + ylab('Proportion of stranding cases') +
  theme_bw() +
  theme(legend.position = 'top') +
  scale_color_manual(values = c('dodgerblue3', 'goldenrod'), name = '')

```


```{r brands per year}

#table of n_ids by year and region
brands <- inits %>%
  dplyr::select(AnimalID, t_0, reg_0) %>% distinct() %>%
  reshape2::dcast(reg_0 ~ t_0, value.var = 'AnimalID') %>%
  transform(reg_0 = factor(reg_0, levels = c('E GULF', 'C GULF', 'E ALEU', 'C ALEU', 'W ALEU'))) %>%
  arrange(reg_0)

```

```{r weights by region}

weights_f <- resights %>%
  distinct(AnimalID, Mass_kg, reg_0, Sex)

weights_m <- resights_m %>%
  distinct(AnimalID, Mass_kg, reg_0, Sex)

weights <- rbind(weights_f, weights_m) %>%
  transform(reg = ifelse(reg_0 %in% c('C ALEU', 'W ALEU'), 'western', 'eastern'))

ggplot(weights, aes(reg, Mass_kg, col = Sex, group = Sex)) +
  geom_violin(draw_quantiles = c(0.025, 0.5, 0.975)) +
  facet_grid(~reg)

weights_sum <- weights %>%
  group_by(Sex, reg) %>%
  dplyr::summarize(mean = mean(Mass_kg), sd = sd(Mass_kg))

```

```{r non natal resights}

res_all <- bind_rows(resights, resights_m) 

res_nonNat <- res_all %>% 
  filter(Region != reg_0) 

#17% of individuals ever sighted outside of non-natal region
n_distinct(res_nonNat$AnimalID)/n_distinct(res_all$AnimalID)


```

