

```{r setup, include = F}

knitr::opts_chunk$set(echo = FALSE, eval = FALSE, message = F, warning = F)

library(here) #v1.0.1
library(dplyr) #v1.0.5
library(coda)
library(nimble) #v0.12.1
library(ggplot2)
library(nimbleEcology)
library(foreach)
library(doParallel)

# source(here::here('scripts', 'PlotTheme.R'))


```

```{r params states}
# Parameters:
# phiP surv pup to yearling
#etc

```

```{r nimble functions}

#state transition - females
getPHI <- nimbleFunction(
  run = function(z=double(0), phiP=double(0), phi1=double(0), phi2=double(0), 
                 phi3=double(0), phi4=double(0), phi5=double(0), phi6=double(0),
                 phi7=double(0), phi8=double(0), phi9=double(0), phi10=double(0), 
                 phi11=double(0), phi12=double(0), phi13=double(0), phi14=double(0),
                 phi15=double(0), phi16=double(0), phiA=double(0)) {
    returnType(double(1))
    ans <- rep(0,19)
    if(z==1)   ans <- c(0,phiP,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-phiP)  #pup
    if(z==2)   ans <- c(0,0,phi1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-phi1)  #yearling   
    if(z==3)   ans <- c(0,0,0,phi2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-phi2)  #2yr
    if(z==4)   ans <- c(0,0,0,0,phi3,0,0,0,0,0,0,0,0,0,0,0,0,0,1-phi3)  #3yr 
    if(z==5)   ans <- c(0,0,0,0,0,phi4,0,0,0,0,0,0,0,0,0,0,0,0,1-phi4)  #4yr
    if(z==6)   ans <- c(0,0,0,0,0,0,phi5,0,0,0,0,0,0,0,0,0,0,0,1-phi5)  #5yr           
    if(z==7)   ans <- c(0,0,0,0,0,0,0,phi6,0,0,0,0,0,0,0,0,0,0,1-phi6)  #6yr 
    if(z==8)   ans <- c(0,0,0,0,0,0,0,0,phi7,0,0,0,0,0,0,0,0,0,1-phi7)       
    if(z==9)   ans <- c(0,0,0,0,0,0,0,0,0,phi8,0,0,0,0,0,0,0,0,1-phi8)       
    if(z==10)  ans <- c(0,0,0,0,0,0,0,0,0,0,phi9,0,0,0,0,0,0,0,1-phi9)   
    if(z==11)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,phi10,0,0,0,0,0,0,1-phi10) 
    if(z==12)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,phi11,0,0,0,0,0,1-phi11) 
    if(z==13)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,phi12,0,0,0,0,1-phi12) 
    if(z==14)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,phi13,0,0,0,1-phi13) 
    if(z==15)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,phi14,0,0,1-phi14) 
    if(z==16)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,phi15,0,1-phi15) 
    if(z==17)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,phi16,1-phi16) 
    if(z==18)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,phiA,1-phiA)       
    if(z==19)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1) #D
    
    return(ans)
 }
)

#observations 
getP <- nimbleFunction(
  run = function(z=double(0), p1=double(0), p2=double(0), p3=double(0), p4=double(0), p5=double(0),
                 p6=double(0), p7=double(0), p8=double(0), p9=double(0), 
                 p10=double(0), p11=double(0), p12=double(0), p13=double(0),
                 p14=double(0), p15=double(0), p16=double(0), 
                 pA=double(0)) {
    returnType(double(1))
    ans <- rep(0,19)
    if(z==1)   ans <- c(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0) #pups seen as pups
    if(z==2)   ans <- c(0,p1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-p1)   #1yr      
    if(z==3)   ans <- c(0,0,p2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-p2)   #2yr
    if(z==4)   ans <- c(0,0,0,p3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-p3)   #3yr
    if(z==5)   ans <- c(0,0,0,0,p4,0,0,0,0,0,0,0,0,0,0,0,0,0,1-p4)   #4yr 
    if(z==6)   ans <- c(0,0,0,0,0,p5,0,0,0,0,0,0,0,0,0,0,0,0,1-p5)   #5yr           
    if(z==7)   ans <- c(0,0,0,0,0,0,p6,0,0,0,0,0,0,0,0,0,0,0,1-p6)   #6yr  
    if(z==8)   ans <- c(0,0,0,0,0,0,0,p7,0,0,0,0,0,0,0,0,0,0,1-p7)   #7yr  
    if(z==9)   ans <- c(0,0,0,0,0,0,0,0,p8,0,0,0,0,0,0,0,0,0,1-p8)   #8yr  
    if(z==10)  ans <- c(0,0,0,0,0,0,0,0,0,p9,0,0,0,0,0,0,0,0,1-p9)   #9yr  
    if(z==11)  ans <- c(0,0,0,0,0,0,0,0,0,0,p10,0,0,0,0,0,0,0,1-p10)   #9yr
    if(z==12)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,p11,0,0,0,0,0,0,1-p11)   #9yr
    if(z==13)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,p12,0,0,0,0,0,1-p12)   #9yr
    if(z==14)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,p13,0,0,0,0,1-p13)   #9yr
    if(z==15)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,p14,0,0,0,1-p14)   #9yr
    if(z==16)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,p15,0,0,1-p15)   #9yr
    if(z==17)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,p16,0,1-p16)   #9yr
    if(z==18)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,pA,1-pA)   #pA
    if(z==19)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1)      #nd
    
    return(ans)
 }
)

```

```{r load data, echo = F, eval = T}

#consider filtering for brands starting in 1994; at least 1990

filter_yr <- 1993

## capture histories
ch_dat_f <- read.csv(here::here('data', 'res_dat_f_1994.csv'),
                   header = T, stringsAsFactors = F) %>% 
  transform(sex == 'Fem') %>%
  filter(cohort > filter_yr) %>%
  # filter(cohort < 2004) %>%
  # filter(cohort < 1990) %>%
    # filter(cohort > 2009) %>%
  dplyr::select(-sex)

ch_dat_m <- read.csv(here::here('data', 'res_dat_m_1994.csv'),
                   header = T, stringsAsFactors = F) %>% 
  filter(cohort > filter_yr) %>%
  # filter(cohort < 2004) %>%
  # filter(cohort > 2009) %>%
    # filter(cohort < 1990) %>%
  dplyr::select(-sex)

## variables and dimensions
n_occasions <- dim(ch_dat_f)[2]-3 #subtract id columns

#need to re-standardize this for males/females
mass_f <- as.numeric(scale(ch_dat_f$wt))
mass_m <- as.numeric(scale(ch_dat_m$wt))

#has weight changed over time?
#not enough to worry about scale()
# ggplot(ch_dat_f, aes(cohort, wt)) +
#   geom_point() +
#   geom_smooth(method = 'loess') +
#   geom_smooth(method = 'lm')

##sst
sst_raw <- read.csv(here('data', '2025_CCEP_sst.csv'), stringsAsFactors = F, header = T)

#from S. Melin in project summary notes docx
#use pupOcttoJune: pup survival from marking to 1st birthday
#use pupAprtoSept: pup survival via gestational foraging success/pup weight effects
#use nonpupJulytoJune: survival of non-pup age classes - sea lion "year"

sst_dat <- sst_raw %>% filter(time > filter_yr) #%>% filter(time > 1993)

#correlation between sst and mass?
plot_dat_f <- ch_dat_f %>%
  dplyr::select(brand, wt, cohort) %>%
  group_by(cohort) %>%
  dplyr::summarize(mean_wt = mean(wt)) %>%
  merge(sst_dat %>% rename(cohort = time), by = 'cohort') %>%
  transform(sex = 'Female')

plot_dat_m <- ch_dat_m %>%
  dplyr::select(brand, wt, cohort) %>%
  group_by(cohort) %>%
  dplyr::summarize(mean_wt = mean(wt)) %>%
  merge(sst_dat %>% rename(cohort = time), by = 'cohort') %>%
  transform(sex = 'Male')

plot_dat <- bind_rows(plot_dat_f, plot_dat_m)
 
#pups (female) are lighter in warmer years (late gestation)
ggplot(plot_dat, aes(pupApriltoSeptSSTAnomalies, mean_wt, col = sex)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  facet_grid(~sex) +
  theme_bw()

#pups (female) are lighter in warmer years (non-breeding yr foraging)
ggplot(plot_dat, aes(nonpupJulytoJuneSSTAnomalies, mean_wt, col = sex)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  facet_grid(~sex) +
  theme_bw()


```

```{r fc inits}

#first capture
# #because not all pups are "resighted" in their branding year - a bit of gymnastics
# yrs <- c(2001:2019)
# fc <- as.numeric(factor(ch_dat$t_0, levels = yrs))

get.first <- function(x) min(which(x==1))
fc <- apply(ch_dat_f[,-c(1:3)], 1, get.first)
fc_m <- apply(ch_dat_m[,-c(1:3)], 1, get.first)

#make 1's for all fc, NA beforehand
ch <- ch_dat_f[,-c(1:3)]
for (i in 1:dim(ch)[1]) {
  ch[i,fc[i]] <- 1
  if(fc[i] > 1) {ch[i, 1:(fc[i]-1)] <- NA }
}

y <- as.matrix(ch)

ch_m <- ch_dat_m[,-c(1:3)]
for (i in 1:dim(ch_m)[1]) {
  ch_m[i,fc_m[i]] <- 1
  if(fc_m[i] > 1) {ch_m[i, 1:(fc_m[i]-1)] <- NA }
}

ym <- as.matrix(ch_m)

# Initial values for possible states
# "NA" for the latent state at all places before an individual was observed

cjs.init <- function(ch, fc){
  inits <- ch    #initialize with observations up until states diverge from observations (4yr olds)
  for(i in 1:dim(ch)[1]) {
    # for(i in 1:10) { 
    inits[i,fc[i]] <- NA #pups at release
      if(n_occasions-fc[i]>=1){   
        inits[i,(fc[i] + 1)] <- 2} #1 yr old
      if(n_occasions-fc[i]>=2){
        inits[i,(fc[i] + 2)] <- 3}  #2 yr old
      if(n_occasions-fc[i]>=3){
        inits[i,(fc[i] + 3)] <- 4} #3 yr old
    if(n_occasions-fc[i]>=4){
        inits[i,(fc[i] + 4)] <- 5}
    if(n_occasions-fc[i]>=5){
        inits[i,(fc[i] + 5)] <- 6}
    if(n_occasions-fc[i]>=6){
        inits[i,(fc[i] + 6)] <- 7}
    if(n_occasions-fc[i]>=7){
        inits[i,(fc[i] + 7)] <- 8}
    if(n_occasions-fc[i]>=8){
        inits[i,(fc[i] + 8)] <- 9}
    if(n_occasions-fc[i]>=9){
        inits[i,(fc[i] + 9)] <- 10}
    
    if(n_occasions-fc[i]>=10){
        inits[i,(fc[i] + 10)] <- 11}
    
    if(n_occasions-fc[i]>=11){
        inits[i,(fc[i] + 11)] <- 12}
    
    if(n_occasions-fc[i]>=12){
        inits[i,(fc[i] + 12)] <- 13}
    
    if(n_occasions-fc[i]>=13){
        inits[i,(fc[i] + 13)] <- 14}
    
    if(n_occasions-fc[i]>=14){
        inits[i,(fc[i] + 14)] <- 15}
    
    if(n_occasions-fc[i]>=15){
        inits[i,(fc[i] + 15)] <- 16}
    
    if(n_occasions-fc[i]>=16){
        inits[i,(fc[i] + 16)] <- 17}
    
      if(n_occasions-fc[i]>=17) {
        inits[i,((fc[i] + 17):n_occasions)] <- 18} #all 17yrs+ are plus group
  } #i
  return(inits)
}

z.init = as.matrix(cjs.init(ch, fc))
z.init.m = as.matrix(cjs.init(ch_m, fc_m))


```


```{r null model}

CSL_CJS <- nimbleCode({

# Priors and constraints
  for (i in 1:n_f) { 
    for (t in 1:(n_occasions - 1)) {
      logit(phiP[i,t]) <- mu.P + b.massP*mass_f[i] #+ epsP[t] + b.siteP[site[i]]
      logit(p1[i,t]) <- mu.p1 #+ eps.p1[t]
    # } #t 
    
    # for (t in 2:(n_occasions-1)) {
      logit(phi1[i,t]) <- mu.1 + b.mass1*mass_f[i] #+ eps1[t] + b.site1[site[i]]
      logit(p2[i,t]) <- mu.p2.3  #+ eps.p2[t]
    # }
    
    # for (t in 3:(n_occasions-1)) {
      logit(phi2[i,t]) <- mu.2.3 #+ eps2[t] + b.site2[site[i]]
      logit(p3[i,t]) <- mu.p2.3 #+ eps.pJ[t]
    # }
    
    # for (t in 4:(n_occasions-1)) { 
      logit(phi3[i,t]) <- mu.2.3 #+ epsJ[t] + b.siteJ[site[i]]
      logit(p4[i,t]) <- mu.p4.6 #+ eps.pJ[t]
    # } #t psi
    
    # for (t in 5:(n_occasions-1)) {
      logit(phi4[i,t]) <- mu.4.6 #+ epsJ[t] + b.siteJ[site[i]]
      logit(p5[i,t]) <- mu.p4.6 #+ eps.pA[t]
    # } #t 
    
    # for (t in 6:(n_occasions-1)) {  
      logit(phi5[i,t]) <- mu.4.6 #+ epsA[t] 
      logit(p6[i,t]) <- mu.p4.6 #+ eps.pA[t]
    # } #t 
    
    # for (t in 7:(n_occasions-1)) {  
      logit(phi6[i,t]) <- mu.4.6 #+ epsA[t] 
      logit(p7[i,t]) <- mu.p7.12 #+ eps.pA[t]
    # } #t 
    
    # for (t in 8:(n_occasions-1)) {  
      logit(phi7[i,t]) <- mu.7.9 #+ epsA[t] 
      logit(p8[i,t]) <- mu.p7.12 #+ eps.pA[t]
    # } #t 
    
    # for (t in 9:(n_occasions-1)) {  
      logit(phi8[i,t]) <- mu.7.9 #+ epsA[t] 
      logit(p9[i,t]) <- mu.p7.12 #+ eps.pA[t]
    # } #t 
    
    # for (t in 10:(n_occasions-1)) {  
      logit(phi9[i,t]) <- mu.7.9 #+ epsA[t] 
      logit(p10[i,t]) <- mu.p7.12 #+ eps.pA[t]
    # } #t 
    
    # for (t in 11:(n_occasions-1)) {  
      logit(phi10[i,t]) <- mu.10.12 # + epsA[t] 
      logit(p11[i,t]) <- mu.p7.12 #+ eps.pA[t]
    # } #t 
  
    # for (t in 12:(n_occasions-1)) {  
      logit(phi11[i,t]) <- mu.10.12 # + epsA[t] 
      logit(p12[i,t]) <- mu.p7.12 #+ eps.pA[t]
    # } #t   
    
        # for (t in 13:(n_occasions-1)) {  
      logit(phi12[i,t]) <- mu.10.12 # + epsA[t] 
      logit(p13[i,t]) <- mu.pA #+ eps.pA[t]
    # } #t  
    
        # for (t in 14:(n_occasions-1)) {  
      logit(phi13[i,t]) <- mu.13.16 # + epsA[t] 
      logit(p14[i,t]) <- mu.pA
    # } #t  
    
        # for (t in 15:(n_occasions-1)) {  
      logit(phi14[i,t]) <- mu.13.16 # + epsA[t] 
      logit(p15[i,t]) <- mu.pA
    # } #t  
    
        # for (t in 16:(n_occasions-1)) {  
      logit(phi15[i,t]) <- mu.13.16 # + epsA[t] 
      logit(p16[i,t]) <- mu.pA
    # } #t  
    
        # for (t in 17:(n_occasions-1)) {  
      logit(phi16[i,t]) <- mu.13.16 # + epsA[t] 
      logit(pA[i,t]) <- mu.pA
    # } #t  
    
        # for (t in 18:(n_occasions-1)) {  
      logit(phiA[i,t]) <- mu.A # + epsA[t] 
    } #t  
  } #females
  
  
  #males
    for (i in 1:n_m) { 
    for (t in 1:(n_occasions - 1)) {
      logit(phiPM[i,t]) <- mu.PM + b.massPM*mass_m[i] #+ epsP[t]
      logit(p1M[i,t]) <- mu.p1 #+ eps.p1[t]
    # } #t 
    
    # for (t in 2:(n_occasions-1)) {
      logit(phi1M[i,t]) <- mu.1M + b.mass1M*mass_m[i] #+ eps1[t] 
      logit(p2M[i,t]) <- mu.p2.3 # + eps.p2.3[t]
    # }
    
    # for (t in 3:(n_occasions-1)) {
      logit(phi2M[i,t]) <- mu.2.3M #+ eps2.3[t]
      logit(p3M[i,t]) <- mu.p2.3 #+ eps.p2.3[t]
    # }
    
    # for (t in 4:(n_occasions-1)) { 
      logit(phi3M[i,t]) <- mu.2.3M #+ eps2.3[t] 
      logit(p4M[i,t]) <- mu.p4.6M #+ eps.p4.6[t]
    # } #t psi
    
    # for (t in 5:(n_occasions-1)) {
      logit(phi4M[i,t]) <- mu.4.6M #+ eps4.6[t] 
      logit(p5M[i,t]) <- mu.p4.6M #+ eps.p4.6[t]
    # } #t 
    
    # for (t in 6:(n_occasions-1)) {  
      logit(phi5M[i,t]) <- mu.4.6M #+ eps4.6[t] 
      logit(p6M[i,t]) <- mu.p4.6M #+ eps.p4.6[t]
    # } #t 
    
    # for (t in 7:(n_occasions-1)) {  
      logit(phi6M[i,t]) <- mu.4.6M #+ eps4.6[t] 
      logit(p7M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    # } #t 
    
    # for (t in 8:(n_occasions-1)) {  
      logit(phi7M[i,t]) <- mu.7.9M #+ epsAM[t] 
      logit(p8M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    # } #t 
    
    # for (t in 9:(n_occasions-1)) {  
      logit(phi8M[i,t]) <- mu.7.9M #+ epsAM[t] 
      logit(p9M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    # } #t 
    
    # for (t in 10:(n_occasions-1)) {  
      logit(phi9M[i,t]) <- mu.7.9M #+ epsAM[t] 
      logit(p10M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    # } #t 
    
    # for (t in 11:(n_occasions-1)) {  
      logit(phi10M[i,t]) <- mu.10.12M #+ epsAM[t] 
      logit(p11M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    # } #t 
  
    # for (t in 12:(n_occasions-1)) {  
      logit(phi11M[i,t]) <- mu.10.12M #+ epsAM[t] 
      logit(p12M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    # } #t   
    
        # for (t in 13:(n_occasions-1)) {  
      logit(phi12M[i,t]) <- mu.10.12M #+ epsAM[t] 
      logit(p13M[i,t]) <- mu.pAM #+ eps.pAM[t]
    # } #t  
    
        # for (t in 14:(n_occasions-1)) {  
      logit(phi13M[i,t]) <- mu.13.16M #+ epsAM[t] 
       logit(p14M[i,t]) <- mu.pAM 
    # } #t  
    
        # for (t in 15:(n_occasions-1)) {  
      logit(phi14M[i,t]) <- mu.13.16M #+ epsAM[t]
       logit(p15M[i,t]) <- mu.pAM 
    # } #t  
    
        # for (t in 16:(n_occasions-1)) {  
      logit(phi15M[i,t]) <- mu.13.16M #+ epsAM[t] 
       logit(p16M[i,t]) <- mu.pAM 
    # } #t  
    
        # for (t in 17:(n_occasions-1)) {  
      logit(phi16M[i,t]) <- mu.13.16M #+ epsAM[t] 
       logit(pAM[i,t]) <- mu.pAM 
    # } #t  
    
        # for (t in 18:(n_occasions-1)) {  
      logit(phiAM[i,t]) <- mu.AM #+ epsAM[t] 
    } #t  
  } #males
    
   
### Priors
    #p
    mu.p1 <- log(int.p1/(1 - int.p1))
    mu.p2.3 <- log(int.p2.3/(1 - int.p2.3))
    mu.p4.6 <- log(int.p4.6/(1 - int.p4.6))
    mu.p7.12 <- log(int.p7.12/(1 - int.p7.12))
    mu.pA <- log(int.pA/(1 - int.pA))

    int.p1 ~ dunif(0,1)
    int.p2.3 ~ dunif(0,1)
    int.p4.6 ~ dunif(0,1)
    int.p7.12 ~ dunif(0,1)
    int.pA ~ dunif(0,1)
    
    mu.p4.6M <- log(int.p4.6M/(1 - int.p4.6M))
    mu.p7.12M <- log(int.p7.12M/(1 - int.p7.12M))
    mu.pAM <- log(int.pAM/(1 - int.pAM))

    int.p4.6M ~ dunif(0,1)
    int.p7.12M ~ dunif(0,1)
    int.pAM ~ dunif(0,1)

    #survival
    mu.P <- log(int.phiP/(1 - int.phiP))
    mu.1 <- log(int.phi1/(1 - int.phi1))
    mu.2.3 <- log(int.phi2.3/(1 - int.phi2.3))
    mu.4.6 <- log(int.phi4.6/(1 - int.phi4.6))
    mu.7.9 <- log(int.phi7.9/(1 - int.phi7.9))
    mu.10.12 <- log(int.phi10.12/(1 - int.phi10.12))
    mu.13.16 <- log(int.phi13.16/(1 - int.phi13.16))
    mu.A <- log(int.phiA/(1 - int.phiA))
    
    int.phiP ~ dunif(0,1)
    int.phi1 ~ dunif(0,1)
    int.phi2.3 ~ dunif(0,1)
    int.phi4.6 ~ dunif(0,1)
    int.phi7.9 ~ dunif(0,1)
    int.phi10.12 ~ dunif(0,1)
    int.phi13.16 ~ dunif(0,1)
    int.phiA ~ dunif(0,1)
    
    #males
    mu.PM <- log(int.phiPM/(1 - int.phiPM))
    mu.1M <- log(int.phi1M/(1 - int.phi1M))
    mu.2.3M <- log(int.phi2.3M/(1 - int.phi2.3M))
    mu.4.6M <- log(int.phi4.6M/(1 - int.phi4.6M))
    mu.7.9M <- log(int.phi7.9M/(1 - int.phi7.9M))
    mu.10.12M <- log(int.phi10.12M/(1 - int.phi10.12M))
    mu.13.16M <- log(int.phi10.12M/(1 - int.phi13.16M))
    mu.AM <- log(int.phiAM/(1 - int.phiAM))
    
    int.phiPM ~ dunif(0,1)
    int.phi1M ~ dunif(0,1)
    int.phi2.3M ~ dunif(0,1)
    int.phi4.6M ~ dunif(0,1)
    int.phi7.9M ~ dunif(0,1)
    int.phi10.12M ~ dunif(0,1)
    int.phi13.16M ~ dunif(0,1)
    int.phiAM ~ dunif(0,1)
    
    b.massP ~ dnorm(0, sd = s.mass)
    b.mass1 ~ dnorm(0, sd = s.mass)
    b.massPM ~ dnorm(0, sd = s.mass)
    b.mass1M ~ dnorm(0, sd = s.mass)
    s.mass ~ dexp(1)
  
    #likelihood
for (i in 1:n_f) { #females
    z[i, fc[i]:fc[i]] <- 1 #pups at first capture

for (t in (fc[i] + 1):n_occasions) {
      z[i,t] ~ dcat(state_probs[i,t-1,1:19])
      y[i,t] ~ dcat(event_probs[i,t,1:19])
      
    state_probs[i,t-1,1:19] <- getPHI(z = z[i,t-1], 
                                      phiP = phiP[i,t-1], phi1 = phi1[i,t-1], phi2 = phi2[i,t-1], 
                                      phi3 = phi3[i,t-1], phi4 = phi4[i,t-1], phi5 = phi5[i,t-1], 
                                      phi6 = phi6[i,t-1], phi7 = phi7[i,t-1], phi8 = phi8[i,t-1],
                                      phi9 = phi9[i,t-1], phi10 = phi10[i,t-1], 
                                      phi11 = phi11[i,t-1], phi12 = phi12[i,t-1],
                                      phi13 = phi13[i,t-1], phi14 = phi14[i,t-1], 
                                      phi15 = phi15[i,t-1], phi16 = phi16[i,t-1],
                                      phiA = phiA[i,t-1])
    
    event_probs[i,t,1:19] <- getP(z = z[i,t], 
                                    p1 = p1[i,t-1], p2 = p2[i,t-1], p3 = p3[i,t-1], 
                                    p4 = p4[i,t-1], p5 = p5[i,t-1], p6 = p6[i,t-1],
                                    p7 = p7[i,t-1], p8 = p8[i,t-1], p9 = p9[i,t-1],
                                  p10 = p10[i,t-1], p11 = p11[i,t-1], p12 = p12[i,t-1],
                                  p13 = p13[i,t-1], p14 = p14[i,t-1], p15 = p15[i,t-1],
                                    p16 = p16[i,t-1], pA = pA[i,t-1])
    } #t likelihood 
} #i likelihood 
    
    for (i in 1:n_m) { #males
    zm[i, fc_m[i]:fc_m[i]] <- 1 #pups at first capture

for (t in (fc_m[i] + 1):n_occasions) {
      zm[i,t] ~ dcat(state_probsM[i,t-1,1:19])
      ym[i,t] ~ dcat(event_probsM[i,t,1:19])
      
    state_probsM[i,t-1,1:19] <- getPHI(z = zm[i,t-1], 
                                      phiP = phiPM[i,t-1], phi1 = phi1M[i,t-1], 
                                      phi2 = phi2M[i,t-1], 
                                      phi3 = phi3M[i,t-1], 
                                      phi4 = phi4M[i,t-1], phi5 = phi5M[i,t-1], 
                                      phi6 = phi6M[i,t-1], phi7 = phi7M[i,t-1], 
                                      phi8 = phi8M[i,t-1], phiA = phiAM[i,t-1],
                                      phi9 = phi9M[i,t-1], phi10 = phi10M[i,t-1],
                                      phi11 = phi11M[i,t-1], phi12 = phi12M[i,t-1],
                                      phi13 = phi13M[i,t-1], phi14 = phi14M[i,t-1],
                                      phi15 = phi15M[i,t-1], phi16 = phi16M[i,t-1])
    
    event_probsM[i,t,1:19] <- getP(z = zm[i,t], 
                                    p1 = p1M[i,t-1], p2 = p2M[i,t-1], p3 = p3M[i,t-1], 
                                    p4 = p4M[i,t-1], p5 = p5M[i,t-1], p6 = p6M[i,t-1],
                                    p7 = p7M[i,t-1], p8 = p8M[i,t-1], p9 = p9M[i,t-1],
                                    p10 = p10M[i,t-1], p11 = p11M[i,t-1], p12 = p12M[i,t-1], 
                                  p13 = p13M[i,t-1],
                                  p14 = p14M[i,t-1], p15 = p15M[i,t-1], p16 = p16M[i,t-1], 
                                  pA = pAM[i,t-1])
    } #t likelihood 
} #i likelihood 
    
}) # mod   

##### run model ####
nim.data <- list(y = y, ym = ym)

nim.constants <- list(n_f = dim(y)[1], n_m = dim(ym)[1], 
                      n_occasions = n_occasions,
                      mass_f = mass_f, mass_m = mass_m, #site = rook, sex = sex,
                      fc = fc, fc_m = fc_m)

inits <- list(int.phiP = 0.9, int.phi1 = 0.9, int.phi2.3 = 0.9, int.phi4.6 = 0.9, int.phi7.9 = 0.9, 
              int.phi10.12 = 0.9, int.phi13.16 = 0.8, int.phiA = 0.6,
              int.phiPM = 0.9, int.phi1M = 0.9, int.phi2.3M = 0.9, int.phi4.6M = 0.9, int.phi7.9M = 0.9, 
              int.phi10.12M = 0.9, int.phi13.16M = 0.8, int.phiAM = 0.6,
              int.p1 = 0.4, int.p2.3 = 0.4, int.p4.6 = 0.5, int.p7.12 = 0.7, int.pA = 0.8,
              int.p4.6M = 0.5, int.p7.12M = 0.7, int.pAM = 0.8,
              b.massP = 0, b.mass1 = 0, b.massPM = 0, b.mass1M = 0, 
              z = z.init, zm = z.init.m)

### parameters
params <- c('int.p1', 'int.p2.3', 'int.p4.6', 'int.p7.12', 'int.pA', 'int.p4.6M', 
            'int.p7.12M', 'int.pAM',
            'b.massP', 'b.mass1', 'b.massPM', 'b.mass1M',
            'int.phiP', 'int.phi1', 'int.phi2.3', 'int.phi4.6', 'int.phi7.9',
            'int.phi10.12', 'int.phi13.16', 'int.phiA',
            'int.phiPM', 'int.phi1M', 'int.phi2.3M', 'int.phi4.6M', 'int.phi7.9M',
            'int.phi10.12M', 'int.phi13.16M', 'int.phiAM')

### run model
# n.iter = 3500; n.chains = 3; n.burnin = 2000; nthin = 3; nAdapt = 20
n.iter = 15000; n.chains = 3; n.burnin = 9000; nthin = 3; nAdapt = 20
n.iter = 400; n.chains = 2; n.burnin = 100; nthin = 2; nAdapt = 20


start <- Sys.time()

cores=detectCores() 
used.cores = min(n.chains, cores) 
cl <- makeCluster(n.chains, setup_strategy = "sequential") 
registerDoParallel(cl) 

foreach(i = 1:n.chains) %dopar% { 
  library(nimble)
  library(here)
  source(here("scripts", "nimbleFunctions.R"))

Rmodel <- nimbleModel(code = CSL_CJS, 
                      constants = nim.constants, data = nim.data, 
                      calculate = F, check = F, inits = inits)

conf <- configureMCMC(Rmodel, monitors = params, control = list(adaptInterval = nAdapt), 
                      thin = nthin, useConjugacy = FALSE)

Rmcmc <- buildMCMC(conf)  #produce uncompiled R mcmc function
Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)

out <- runMCMC(Cmcmc, niter = n.iter, nburnin = n.burnin, 
               # nchains = n.chains, 
               nchains = 1,
               inits = inits,
                 setSeed = FALSE, progressBar = TRUE,
               samplesAsCodaMCMC = TRUE)


  saveRDS(out, here('results', paste("out.parallel_null_", i, ".RDS", sep = ""))) 
  
} # closes parallel loop

out_1 <- readRDS(here::here('results', paste("out.parallel_null_", "1.RDS", sep = "")))
out_2 <- readRDS(here::here('results', paste("out.parallel_null_", "2.RDS", sep = "")))
out_3 <- readRDS(here::here('results', paste("out.parallel_null_", "3.RDS", sep = "")))

library(coda)
out <- list(`out_1`, `out_2`, `out_3`) %>% as.mcmc.list()

# saveRDS(out, here::here('results', 'out_null.RDS'))

```


```{r sst model}

CSL_CJS <- nimbleCode({

# Priors and constraints
  for (i in 1:n_f) { 
    for (t in 1:(n_occasions - 1)) {
      logit(phiP[i,t]) <- mu.P + 
        b.sst.P*sst_pupForage[t] #+
        # b.massP*mass_f[i] #+ epsP[t] + b.siteP[site[i]]
      logit(p1[i,t]) <- mu.p1 #+ eps.p1[t]
    } #t 
    
    for (t in 2:(n_occasions-1)) {
      logit(phi1[i,t]) <- mu.1 + 
        b.sst.np*sst_np[t] #+
        # b.mass1*mass_f[i] #+ eps1[t] + b.site1[site[i]]
      logit(p2[i,t]) <- mu.p2.3  #+ eps.p2[t]
    }
    
    for (t in 3:(n_occasions-1)) {
      logit(phi2[i,t]) <- mu.2.3 + b.sst.np*sst_np[t] 
      logit(p3[i,t]) <- mu.p2.3 #+ eps.pJ[t]
    }
    
    for (t in 4:(n_occasions-1)) { 
      logit(phi3[i,t]) <- mu.2.3 + b.sst.np*sst_np[t] #+ epsJ[t] + b.siteJ[site[i]]
      logit(p4[i,t]) <- mu.p4.6 #+ eps.pJ[t]
    } #t psi
    
    for (t in 5:(n_occasions-1)) {
      logit(phi4[i,t]) <- mu.4.6 #+ epsJ[t] + b.siteJ[site[i]]
      logit(p5[i,t]) <- mu.p4.6 #+ eps.pA[t]
    } #t 
    
    for (t in 6:(n_occasions-1)) {  
      logit(phi5[i,t]) <- mu.4.6 #+ epsA[t] 
      logit(p6[i,t]) <- mu.p4.6 #+ eps.pA[t]
    } #t 
    
    for (t in 7:(n_occasions-1)) {  
      logit(phi6[i,t]) <- mu.4.6 #+ epsA[t] 
      logit(p7[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t 
    
    for (t in 8:(n_occasions-1)) {  
      logit(phi7[i,t]) <- mu.7.9 #+ epsA[t] 
      logit(p8[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t 
    
    for (t in 9:(n_occasions-1)) {  
      logit(phi8[i,t]) <- mu.7.9 #+ epsA[t] 
      logit(p9[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t 
    
    for (t in 10:(n_occasions-1)) {  
      logit(phi9[i,t]) <- mu.7.9 #+ epsA[t] 
      logit(p10[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t 
    
    for (t in 11:(n_occasions-1)) {  
      logit(phi10[i,t]) <- mu.10.12 # + epsA[t] 
      logit(p11[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t 
  
    for (t in 12:(n_occasions-1)) {  
      logit(phi11[i,t]) <- mu.10.12 # + epsA[t] 
      logit(p12[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t   
    
        for (t in 13:(n_occasions-1)) {  
      logit(phi12[i,t]) <- mu.10.12 # + epsA[t] 
      logit(pA[i,t]) <- mu.pA #+ eps.pA[t]
    } #t  
    
        for (t in 14:(n_occasions-1)) {  
      logit(phi13[i,t]) <- mu.13.16 # + epsA[t] 
    } #t  
    
        for (t in 15:(n_occasions-1)) {  
      logit(phi14[i,t]) <- mu.13.16 # + epsA[t] 
    } #t  
    
        for (t in 16:(n_occasions-1)) {  
      logit(phi15[i,t]) <- mu.13.16 # + epsA[t] 
    } #t  
    
        for (t in 17:(n_occasions-1)) {  
      logit(phi16[i,t]) <- mu.13.16 # + epsA[t] 
    } #t  
    
        for (t in 18:(n_occasions-1)) {  
      logit(phiA[i,t]) <- mu.A # + epsA[t] 
    } #t  
  } #females
  
  
  #males
    for (i in 1:n_m) { 
    for (t in 1:(n_occasions - 1)) {
      logit(phiPM[i,t]) <- mu.PM + 
        b.sst.P*sst_pupForage[t] #+ epsP[t]
      logit(p1M[i,t]) <- mu.p1 #+ eps.p1[t]
    } #t 
    
    for (t in 2:(n_occasions-1)) {
      logit(phi1M[i,t]) <- mu.1M + 
        b.sst.np*sst_np[t] #+ b.mass1M*mass_m[i] #+ eps1[t] 
      logit(p2M[i,t]) <- mu.p2.3 # + eps.p2.3[t]
    }
    
    for (t in 3:(n_occasions-1)) {
      logit(phi2M[i,t]) <- mu.2.3M + b.sst.np*sst_np[t]#+ eps2.3[t]
      logit(p3M[i,t]) <- mu.p2.3 #+ eps.p2.3[t]
    }
    
    for (t in 4:(n_occasions-1)) { 
      logit(phi3M[i,t]) <- mu.2.3M + b.sst.np*sst_np[t] #+ eps2.3[t] 
      logit(p4M[i,t]) <- mu.p4.6M #+ eps.p4.6[t]
    } #t psi
    
    for (t in 5:(n_occasions-1)) {
      logit(phi4M[i,t]) <- mu.4.6M #+ eps4.6[t] 
      logit(p5M[i,t]) <- mu.p4.6M #+ eps.p4.6[t]
    } #t 
    
    for (t in 6:(n_occasions-1)) {  
      logit(phi5M[i,t]) <- mu.4.6M #+ eps4.6[t] 
      logit(p6M[i,t]) <- mu.p4.6M #+ eps.p4.6[t]
    } #t 
    
    for (t in 7:(n_occasions-1)) {  
      logit(phi6M[i,t]) <- mu.4.6M #+ eps4.6[t] 
      logit(p7M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    } #t 
    
    for (t in 8:(n_occasions-1)) {  
      logit(phi7M[i,t]) <- mu.7.9M #+ epsAM[t] 
      logit(p8M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    } #t 
    
    for (t in 9:(n_occasions-1)) {  
      logit(phi8M[i,t]) <- mu.7.9M #+ epsAM[t] 
      logit(p9M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    } #t 
    
    for (t in 10:(n_occasions-1)) {  
      logit(phi9M[i,t]) <- mu.7.9M #+ epsAM[t] 
      logit(p10M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    } #t 
    
    for (t in 11:(n_occasions-1)) {  
      logit(phi10M[i,t]) <- mu.10.12M #+ epsAM[t] 
      logit(p11M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    } #t 
  
    for (t in 12:(n_occasions-1)) {  
      logit(phi11M[i,t]) <- mu.10.12M #+ epsAM[t] 
      logit(p12M[i,t]) <- mu.p7.12M #+ eps.pAM[t]
    } #t   
    
        for (t in 13:(n_occasions-1)) {  
      logit(phi12M[i,t]) <- mu.10.12M #+ epsAM[t] 
      logit(p13M[i,t]) <- mu.pAM #+ eps.pAM[t]
    } #t  
    
        for (t in 14:(n_occasions-1)) {  
      logit(phi13M[i,t]) <- mu.13.16M #+ epsAM[t] 
       logit(p14M[i,t]) <- mu.pAM 
    } #t  
    
        for (t in 15:(n_occasions-1)) {  
      logit(phi14M[i,t]) <- mu.13.16M #+ epsAM[t]
       logit(p15M[i,t]) <- mu.pAM 
    } #t  
    
        for (t in 16:(n_occasions-1)) {  
      logit(phi15M[i,t]) <- mu.13.16M #+ epsAM[t] 
       logit(p16M[i,t]) <- mu.pAM 
    } #t  
    
        for (t in 17:(n_occasions-1)) {  
      logit(phi16M[i,t]) <- mu.13.16M #+ epsAM[t] 
       logit(pAM[i,t]) <- mu.pAM 
    } #t  
    
        for (t in 18:(n_occasions-1)) {  
      logit(phiAM[i,t]) <- mu.AM #+ epsAM[t] 
    } #t  
  } #males
    
   
### Priors
    #p
    mu.p1 <- log(int.p1/(1 - int.p1))
    mu.p2.3 <- log(int.p2.3/(1 - int.p2.3))
    mu.p4.6 <- log(int.p4.6/(1 - int.p4.6))
    mu.p7.12 <- log(int.p7.12/(1 - int.p7.12))
    mu.pA <- log(int.pA/(1 - int.pA))

    int.p1 ~ dunif(0,1)
    int.p2.3 ~ dunif(0,1)
    int.p4.6 ~ dunif(0,1)
    int.p7.12 ~ dunif(0,1)
    int.pA ~ dunif(0,1)
    
    mu.p4.6M <- log(int.p4.6M/(1 - int.p4.6M))
    mu.p7.12M <- log(int.p7.12M/(1 - int.p7.12M))
    mu.pAM <- log(int.pAM/(1 - int.pAM))

    int.p4.6M ~ dunif(0,1)
    int.p7.12M ~ dunif(0,1)
    int.pAM ~ dunif(0,1)

    #survival
    mu.P <- log(int.phiP/(1 - int.phiP))
    mu.1 <- log(int.phi1/(1 - int.phi1))
    mu.2.3 <- log(int.phi2.3/(1 - int.phi2.3))
    mu.4.6 <- log(int.phi4.6/(1 - int.phi4.6))
    mu.7.9 <- log(int.phi7.9/(1 - int.phi7.9))
    mu.10.12 <- log(int.phi10.12/(1 - int.phi10.12))
    mu.13.16 <- log(int.phi13.16/(1 - int.phi13.16))
    mu.A <- log(int.phiA/(1 - int.phiA))
    
    int.phiP ~ dunif(0,1)
    int.phi1 ~ dunif(0,1)
    int.phi2.3 ~ dunif(0,1)
    int.phi4.6 ~ dunif(0,1)
    int.phi7.9 ~ dunif(0,1)
    int.phi10.12 ~ dunif(0,1)
    int.phi13.16 ~ dunif(0,1)
    int.phiA ~ dunif(0,1)
    
    #males
    mu.PM <- log(int.phiPM/(1 - int.phiPM))
    mu.1M <- log(int.phi1M/(1 - int.phi1M))
    mu.2.3M <- log(int.phi2.3M/(1 - int.phi2.3M))
    mu.4.6M <- log(int.phi4.6M/(1 - int.phi4.6M))
    mu.7.9M <- log(int.phi7.9M/(1 - int.phi7.9M))
    mu.10.12M <- log(int.phi10.12M/(1 - int.phi10.12M))
    mu.13.16M <- log(int.phi10.12M/(1 - int.phi13.16M))
    mu.AM <- log(int.phiAM/(1 - int.phiAM))
    
    int.phiPM ~ dunif(0,1)
    int.phi1M ~ dunif(0,1)
    int.phi2.3M ~ dunif(0,1)
    int.phi4.6M ~ dunif(0,1)
    int.phi7.9M ~ dunif(0,1)
    int.phi10.12M ~ dunif(0,1)
    int.phi13.16M ~ dunif(0,1)
    int.phiAM ~ dunif(0,1)
    
    # b.massP ~ dnorm(0, sd = s.mass)
    # b.mass1 ~ dnorm(0, sd = s.mass)
    # b.massPM ~ dnorm(0, sd = s.mass)
    # b.mass1M ~ dnorm(0, sd = s.mass)
    # s.mass ~ dexp(1)
    
    b.sst.p ~ dnorm(0,sd = s.sst)
    b.sst.np ~ dnorm(0, sd = s.sst)
    s.sst ~ dexp(1)
  
    #likelihood
for (i in 1:n_f) { #females
    z[i, fc[i]:fc[i]] <- 1 #pups at first capture

for (t in (fc[i] + 1):n_occasions) {
      z[i,t] ~ dcat(state_probs[i,t-1,1:19])
      y[i,t] ~ dcat(event_probs[i,t,1:19])
      
    state_probs[i,t-1,1:19] <- getPHI(z = z[i,t-1], 
                                      phiP = phiP[i,t-1], phi1 = phi1[i,t-1], phi2 = phi2[i,t-1], 
                                      phi3 = phi3[i,t-1], phi4 = phi4[i,t-1], phi5 = phi5[i,t-1], 
                                      phi6 = phi6[i,t-1], phi7 = phi7[i,t-1], phi8 = phi8[i,t-1],
                                      phi9 = phi9[i,t-1], phi10 = phi10[i,t-1], 
                                      phi11 = phi11[i,t-1], phi12 = phi12[i,t-1],
                                      phi13 = phi13[i,t-1], phi14 = phi14[i,t-1], 
                                      phi15 = phi15[i,t-1], phi16 = phi16[i,t-1],
                                      phiA = phiA[i,t-1])
    
    event_probs[i,t,1:19] <- getP(z = z[i,t], 
                                    p1 = p1[i,t-1], p2 = p2[i,t-1], p3 = p3[i,t-1], 
                                    p4 = p4[i,t-1], p5 = p5[i,t-1], p6 = p6[i,t-1],
                                    p7 = p7[i,t-1], p8 = p8[i,t-1], p9 = p9[i,t-1],
                                  p10 = p10[i,t-1], p11 = p11[i,t-1], p12 = p12[i,t-1],
                                  p13 = p13[i,t-1], p14 = p14[i,t-1], p15 = p15[i,t-1],
                                    p16 = p16[i,t-1], pA = pA[i,t-1])
    } #t likelihood 
} #i likelihood 
    
    for (i in 1:n_m) { #males
    zm[i, fc_m[i]:fc_m[i]] <- 1 #pups at first capture

for (t in (fc_m[i] + 1):n_occasions) {
      zm[i,t] ~ dcat(state_probsM[i,t-1,1:19])
      ym[i,t] ~ dcat(event_probsM[i,t,1:19])
      
    state_probsM[i,t-1,1:19] <- getPHI(z = zm[i,t-1], 
                                      phiP = phiPM[i,t-1], phi1 = phi1M[i,t-1], 
                                      phi2 = phi2M[i,t-1], 
                                      phi3 = phi3M[i,t-1], 
                                      phi4 = phi4M[i,t-1], phi5 = phi5M[i,t-1], 
                                      phi6 = phi6M[i,t-1], phi7 = phi7M[i,t-1], 
                                      phi8 = phi8M[i,t-1], phiA = phiAM[i,t-1],
                                      phi9 = phi9M[i,t-1], phi10 = phi10M[i,t-1],
                                      phi11 = phi11M[i,t-1], phi12 = phi12M[i,t-1],
                                      phi13 = phi13M[i,t-1], phi14 = phi14M[i,t-1],
                                      phi15 = phi15M[i,t-1], phi16 = phi16M[i,t-1])
    
    event_probsM[i,t,1:19] <- getP(z = zm[i,t], 
                                    p1 = p1M[i,t-1], p2 = p2M[i,t-1], p3 = p3M[i,t-1], 
                                    p4 = p4M[i,t-1], p5 = p5M[i,t-1], p6 = p6M[i,t-1],
                                    p7 = p7M[i,t-1], p8 = p8M[i,t-1], p9 = p9M[i,t-1],
                                    p10 = p10M[i,t-1], p11 = p11M[i,t-1], p12 = p12M[i,t-1], 
                                  p13 = p13M[i,t-1],
                                  p14 = p14M[i,t-1], p15 = p15M[i,t-1], p16 = p16M[i,t-1], 
                                  pA = pAM[i,t-1])
    } #t likelihood 
} #i likelihood 
    
}) # mod   

##### run model ####
nim.data <- list(y = y, ym = ym)

nim.constants <- list(n_f = dim(y)[1], n_m = dim(ym)[1], 
                      n_occasions = n_occasions,
                      sst_pupForage = sst_dat[,2],
                      sst_np = sst_dat[,4],
                      mass_f = mass_f, mass_m = mass_m, #site = rook, sex = sex,
                      fc = fc, fc_m = fc_m)

inits <- list(int.phiP = 0.9, int.phi1 = 0.9, int.phi2.3 = 0.9, int.phi4.6 = 0.9, int.phi7.9 = 0.9, 
              int.phi10.12 = 0.9, int.phi13.16 = 0.8, int.phiA = 0.6,
              int.phiPM = 0.9, int.phi1M = 0.9, int.phi2.3M = 0.9, int.phi4.6M = 0.9, int.phi7.9M = 0.9, 
              int.phi10.12M = 0.9, int.phi13.16M = 0.8, int.phiAM = 0.6,
              int.p1 = 0.4, int.p2.3 = 0.4, int.p4.6 = 0.5, int.p7.12 = 0.7, int.pA = 0.8,
              int.p4.6M = 0.5, int.p7.12M = 0.7, int.pAM = 0.8,
              b.massP = 0, b.mass1 = 0, b.massPM = 0, b.mass1M = 0, 
              z = z.init, zm = z.init.m)

### parameters
params <- c('int.p1', 'int.p2.3', 'int.p4.6', 'int.p7.12', 'int.pA', 'int.p4.6M', 
            'int.p7.12M', 'int.pAM',
            # 'b.massP', 'b.mass1', 'b.massPM', 'b.mass1M',
            'b.sst.p', 'b.sst.np',
            'int.phiP', 'int.phi1', 'int.phi2.3', 'int.phi4.6', 'int.phi7.9',
            'int.phi10.12', 'int.phi13.16', 'int.phiA',
            'int.phiPM', 'int.phi1M', 'int.phi2.3M', 'int.phi4.6M', 'int.phi7.9M',
            'int.phi10.12M', 'int.phi13.16M', 'int.phiAM')

### run model
# n.iter = 3500; n.chains = 3; n.burnin = 2000; nthin = 3; nAdapt = 20
n.iter = 15000; n.chains = 3; n.burnin = 9000; nthin = 3; nAdapt = 20
# n.iter = 400; n.chains = 1; n.burnin = 100; nthin = 2; nAdapt = 20


start <- Sys.time()

cores=detectCores() 
used.cores = min(n.chains, cores) 
cl <- makeCluster(n.chains, setup_strategy = "sequential") 
registerDoParallel(cl) 

foreach(i = 1:n.chains) %dopar% { 
  library(nimble)
  library(here)
  source(here("scripts", "nimbleFunctions.R"))

Rmodel <- nimbleModel(code = CSL_CJS, 
                      constants = nim.constants, data = nim.data, 
                      calculate = F, check = F, inits = inits)

conf <- configureMCMC(Rmodel, monitors = params, control = list(adaptInterval = nAdapt), 
                      thin = nthin, useConjugacy = FALSE)

Rmcmc <- buildMCMC(conf)  #produce uncompiled R mcmc function
Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)

out <- runMCMC(Cmcmc, niter = n.iter, nburnin = n.burnin, 
               # nchains = n.chains, 
               nchains = 1,
               inits = inits,
                 setSeed = FALSE, progressBar = TRUE,
               samplesAsCodaMCMC = TRUE)


  saveRDS(out, here('results', paste("out.parallel_sst_", i, ".RDS", sep = ""))) 
  
} # closes parallel loop

out_1 <- readRDS(here::here('results', paste("out.parallel_sst_", "1.RDS", sep = "")))
out_2 <- readRDS(here::here('results', paste("out.parallel_sst_", "2.RDS", sep = "")))
out_3 <- readRDS(here::here('results', paste("out.parallel_sst_", "3.RDS", sep = "")))

library(coda)
out <- list(`out_1`, `out_2`, `out_3`) %>% as.mcmc.list()

saveRDS(out, here::here('results', 'out_sst.RDS')) 

```


```{r temporal variance model}

CSL_CJS <- nimbleCode({

# Priors and constraints
  for (i in 1:n_f) { 
    for (t in 1:(n_occasions - 1)) {
      logit(phiP[i,t]) <- mu.P + b.massP*mass_f[i] + epsP[t] 
      logit(p1[i,t]) <- mu.p1 + eps.p1[t]
    # } #t 
    
    # for (t in 2:(n_occasions-1)) {
      logit(phi1[i,t]) <- mu.1 + b.mass1*mass_f[i] + eps1[t] 
      logit(p2[i,t]) <- mu.p2.3  + eps.p2.3[t]
    # }
    
    # for (t in 3:(n_occasions-1)) {
      logit(phi2[i,t]) <- mu.2.3 + eps2.3[t] 
      logit(p3[i,t]) <- mu.p2.3 + eps.p2.3[t]
    # }
    
    # for (t in 4:(n_occasions-1)) { 
      logit(phi3[i,t]) <- mu.2.3 + eps2.3[t] 
      logit(p4[i,t]) <- mu.p4.6 + eps.p4.6[t]
    # } #t 
    
    # for (t in 5:(n_occasions-1)) {
      logit(phi4[i,t]) <- mu.4.6 + eps4.6[t] 
      logit(p5[i,t]) <- mu.p4.6 + eps.p4.6[t]
    # } #t 
    
    # for (t in 6:(n_occasions-1)) {  
      logit(phi5[i,t]) <- mu.4.6 + eps4.6[t]
      logit(p6[i,t]) <- mu.p4.6 + eps.p4.6[t]
    # } #t 
    
    # for (t in 7:(n_occasions-1)) {  
      logit(phi6[i,t]) <- mu.4.6 + eps4.6[t]
      logit(p7[i,t]) <- mu.p7.12 + eps.pA[t]
    # } #t 
    
    # for (t in 8:(n_occasions-1)) {  
      logit(phi7[i,t]) <- mu.7.9 + eps7.9[t]
      logit(p8[i,t]) <- mu.p7.12 + eps.pA[t]
    # } #t 
    
    # for (t in 9:(n_occasions-1)) {  
      logit(phi8[i,t]) <- mu.7.9 + eps7.9[t]
      logit(p9[i,t]) <- mu.p7.12 + eps.pA[t]
    # } #t 
    
    # for (t in 10:(n_occasions-1)) {  
      logit(phi9[i,t]) <- mu.7.9 + eps7.9[t]
      logit(p10[i,t]) <- mu.p7.12 + eps.pA[t]
    # } #t 
    
    # for (t in 11:(n_occasions-1)) {  
      logit(phi10[i,t]) <- mu.10.12 + epsA[t]
      logit(p11[i,t]) <- mu.p7.12 + eps.pA[t]
    # } #t 
  
    # for (t in 12:(n_occasions-1)) {  
      logit(phi11[i,t]) <- mu.10.12 + epsA[t] 
      logit(p12[i,t]) <- mu.p7.12 + eps.pA[t]
    # } #t   
    
        # for (t in 13:(n_occasions-1)) {  
      logit(phi12[i,t]) <- mu.10.12 + epsA[t] 
      logit(p13[i,t]) <- mu.pA + eps.pA[t]
    # } #t  
    
        # for (t in 14:(n_occasions-1)) {  
      logit(phi13[i,t]) <- mu.13.16 + epsA[t] 
      logit(p14[i,t]) <- mu.pA + eps.pA[t]
    # } #t  
    
        # for (t in 15:(n_occasions-1)) {  
      logit(phi14[i,t]) <- mu.13.16 + epsA[t] 
      logit(p15[i,t]) <- mu.pA + eps.pA[t]
    # } #t  
    
        # for (t in 16:(n_occasions-1)) {  
      logit(phi15[i,t]) <- mu.13.16 + epsA[t] 
      logit(p16[i,t]) <- mu.pA + eps.pA[t]
    # } #t  
    
        # for (t in 17:(n_occasions-1)) {  
      logit(phi16[i,t]) <- mu.13.16 + epsA[t] 
      logit(pA[i,t]) <- mu.pA + eps.pA[t]
    # } #t  
    
        # for (t in 18:(n_occasions-1)) {  
      logit(phiA[i,t]) <- mu.A + epsA[t] 
    } #t  
  } #females
  
  
  #males
    for (i in 1:n_m) { 
    for (t in 1:(n_occasions - 1)) {
      logit(phiPM[i,t]) <- mu.PM + b.massPM*mass_m[i] + epsP[t] 
      logit(p1M[i,t]) <- mu.p1 + eps.p1[t]
    # } #t 
    
    # for (t in 2:(n_occasions-1)) {
      logit(phi1M[i,t]) <- mu.1M + b.mass1M*mass_m[i] + eps1[t] 
      logit(p2M[i,t]) <- mu.p2.3  + eps.p2.3[t]
    # }
    
    # for (t in 3:(n_occasions-1)) {
      logit(phi2M[i,t]) <- mu.2.3M + eps2.3[t] 
      logit(p3M[i,t]) <- mu.p2.3 + eps.p2.3[t]
    # }
    
    # for (t in 4:(n_occasions-1)) { 
      logit(phi3M[i,t]) <- mu.2.3M + eps2.3[t] 
      logit(p4M[i,t]) <- mu.p4.6M + eps.p4.6M[t]
    # } #t psi
    
    # for (t in 5:(n_occasions-1)) {
      logit(phi4M[i,t]) <- mu.4.6M + eps4.6M[t] 
      logit(p5M[i,t]) <- mu.p4.6M + eps.p4.6M[t]
    # } #t 
    
    # for (t in 6:(n_occasions-1)) {  
      logit(phi5M[i,t]) <- mu.4.6M + eps4.6M[t] 
      logit(p6M[i,t]) <- mu.p4.6M + eps.p4.6M[t]
    # } #t 
    
    # for (t in 7:(n_occasions-1)) {  
      logit(phi6M[i,t]) <- mu.4.6M + eps4.6M[t] 
      logit(p7M[i,t]) <- mu.p7.12M + eps.pAM[t]
    # } #t 
    
    # for (t in 8:(n_occasions-1)) {  
      logit(phi7M[i,t]) <- mu.7.9M + eps7.9M[t] 
      logit(p8M[i,t]) <- mu.p7.12M + eps.pAM[t]
    # } #t 
    
    # for (t in 9:(n_occasions-1)) {  
      logit(phi8M[i,t]) <- mu.7.9M + eps7.9M[t] 
      logit(p9M[i,t]) <- mu.p7.12M + eps.pAM[t]
    # } #t 
    
    # for (t in 10:(n_occasions-1)) {  
      logit(phi9M[i,t]) <- mu.7.9M + eps7.9M[t] 
      logit(p10M[i,t]) <- mu.p7.12M + eps.pAM[t]
    # } #t 
    
    # for (t in 11:(n_occasions-1)) {  
      logit(phi10M[i,t]) <- mu.10.12M  + epsAM[t] 
      logit(p11M[i,t]) <- mu.p7.12M + eps.pAM[t]
    # } #t 
  
    # for (t in 12:(n_occasions-1)) {  
      logit(phi11M[i,t]) <- mu.10.12M  + epsAM[t]  
      logit(p12M[i,t]) <- mu.p7.12M + eps.pAM[t]
    # } #t   
    
        # for (t in 13:(n_occasions-1)) {  
      logit(phi12M[i,t]) <- mu.10.12M + epsAM[t] 
      logit(p13M[i,t]) <- mu.pAM + eps.pAM[t]
    # } #t  
    
        # for (t in 14:(n_occasions-1)) {  
      logit(phi13M[i,t]) <- mu.13.16M + epsAM[t] 
      logit(p14M[i,t]) <- mu.pAM + eps.pAM[t]
    # } #t  
    
        # for (t in 15:(n_occasions-1)) {  
      logit(phi14M[i,t]) <- mu.13.16M + epsAM[t] 
      logit(p15M[i,t]) <- mu.pAM + eps.pAM[t]
    # } #t  
    
        # for (t in 16:(n_occasions-1)) {  
      logit(phi15M[i,t]) <- mu.13.16M  + epsAM[t] 
      logit(p16M[i,t]) <- mu.pAM + eps.pAM[t]
    # } #t  
    
        # for (t in 17:(n_occasions-1)) {  
      logit(phi16M[i,t]) <- mu.13.16M + epsAM[t] 
      logit(pAM[i,t]) <- mu.pAM + eps.pAM[t]
    # } #t  
    
        # for (t in 18:(n_occasions-1)) {  
      logit(phiAM[i,t]) <- mu.AM + epsAM[t] 
    } #t  
  } #males
  
  for (t in 1:(n_occasions - 1)) {
      epsP[t] ~ dnorm(0, sd = sigmaP)
      eps.p1[t] ~ dnorm(0, sd = sigma.p1)
    # } #t

    # for (t in 2:(n_occasions-1)) {
      eps1[t] ~ dnorm(0, sd = sigma1)
      eps.p2.3[t] ~ dnorm(0, sd = sigma.p2)
    # }

    # for (t in 3:(n_occasions-1)) {
      eps2.3[t] ~ dnorm(0, sd = sigma2)
    # }
  
    # for (t in 4:(n_occasions-1)) {
      eps.p4.6[t] ~ dnorm(0, sd = sigma.pJ)
      eps.p4.6M[t] ~ dnorm(0, sd = sigma.pJ)
    # }

    # for (t in 5:(n_occasions-1)) {
      eps4.6[t] ~ dnorm(0, sd = sigmaJ)
      eps4.6M[t] ~ dnorm(0, sd = sigmaJ)
    # } #t
  
     # for (t in 7:(n_occasions-1)) {
      eps.pA[t] ~ dnorm(0, sd = sigma.pA)
      eps.pAM[t] ~ dnorm(0, sd = sigma.pA)
    # } #t

    # for (t in 8:(n_occasions-1)) {
      eps7.9[t] ~ dnorm(0, sd = sigmaA)
      eps7.9M[t] ~ dnorm(0, sd = sigmaA)
    # } #t

    # for (t in 11:(n_occasions-1)) {
      epsA[t] ~ dnorm(0, sd = sigmaA)
      epsAM[t] ~ dnorm(0, sd = sigmaA)
    } #t
  
    sigmaP ~ dexp(1)
    sigma1 ~ dexp(1)
    sigma2 ~ dexp(1)
    sigmaJ ~ dexp(1)
    sigmaA ~ dexp(1)
    sigma.p1 ~ dexp(1)
    sigma.p2 ~ dexp(1)
    sigma.pJ ~ dexp(1)
    sigma.pA ~ dexp(1)
    
### Priors
    #p
    mu.p1 <- log(int.p1/(1 - int.p1))
    mu.p2.3 <- log(int.p2.3/(1 - int.p2.3))
    mu.p4.6 <- log(int.p4.6/(1 - int.p4.6))
    mu.p7.12 <- log(int.p7.12/(1 - int.p7.12))
    mu.pA <- log(int.pA/(1 - int.pA))

    int.p1 ~ dunif(0,1)
    int.p2.3 ~ dunif(0,1)
    int.p4.6 ~ dunif(0,1)
    int.p7.12 ~ dunif(0,1)
    int.pA ~ dunif(0,1)

    mu.p7.12M <- log(int.p7.12M/(1 - int.p7.12M))
    mu.pAM <- log(int.pAM/(1 - int.pAM))
    mu.p4.6M <- log(int.p4.6M/(1 - int.p4.6M))
    int.p7.12M ~ dunif(0,1)
    int.pAM ~ dunif(0,1)
    int.p4.6M ~ dunif(0,1)

    mu.P <- log(int.phiP/(1 - int.phiP))
    mu.1 <- log(int.phi1/(1 - int.phi1))
    mu.2.3 <- log(int.phi2.3/(1 - int.phi2.3))
    mu.4.6 <- log(int.phi4.6/(1 - int.phi4.6))
    mu.7.9 <- log(int.phi7.9/(1 - int.phi7.9))
    mu.10.12 <- log(int.phi10.12/(1 - int.phi10.12))
    mu.13.16 <- log(int.phi13.16/(1 - int.phi13.16))
    mu.A <- log(int.phiA/(1 - int.phiA))
    
    int.phiP ~ dunif(0,1)
    int.phi1 ~ dunif(0,1)
    int.phi2.3 ~ dunif(0,1)
    int.phi4.6 ~ dunif(0,1)
    int.phi7.9 ~ dunif(0,1)
    int.phi10.12 ~ dunif(0,1)
    int.phi13.16 ~ dunif(0,1)
    int.phiA ~ dunif(0,1)
    
    #males
    mu.PM <- log(int.phiPM/(1 - int.phiPM))
    mu.1M <- log(int.phi1M/(1 - int.phi1M))
    mu.2.3M <- log(int.phi2.3M/(1 - int.phi2.3M))
    mu.4.6M <- log(int.phi4.6M/(1 - int.phi4.6M))
    mu.7.9M <- log(int.phi7.9M/(1 - int.phi7.9M))
    mu.10.12M <- log(int.phi10.12M/(1 - int.phi10.12M))
    mu.13.16M <- log(int.phi10.12M/(1 - int.phi13.16M))
    mu.AM <- log(int.phiAM/(1 - int.phiAM))
    
    int.phiPM ~ dunif(0,1)
    int.phi1M ~ dunif(0,1)
    int.phi2.3M ~ dunif(0,1)
    int.phi4.6M ~ dunif(0,1)
    int.phi7.9M ~ dunif(0,1)
    int.phi10.12M ~ dunif(0,1)
    int.phi13.16M ~ dunif(0,1)
    int.phiAM ~ dunif(0,1)
    
    b.massP ~ dnorm(0, sd = s.mass)
    b.mass1 ~ dnorm(0, sd = s.mass)
    b.massPM ~ dnorm(0, sd = s.mass)
    b.mass1M ~ dnorm(0, sd = s.mass)
    s.mass ~ dexp(1)
    
    
    #backtransformed probability scale
    for (t in 1:(n_occasions-1)){
      p1.prob[t] <- 1/(1+exp(-(mu.p1 + eps.p1[t])))
      p2.3.prob[t] <- 1/(1+exp(-(mu.p2.3 + eps.p2.3[t])))

      p4.6.prob[t] <- 1/(1+exp(-(mu.p4.6 + eps.p4.6[t])))
      p4.6M.prob[t] <- 1/(1+exp(-(mu.p4.6M + eps.p4.6M[t])))
       
      p7.12.prob[t] <- 1/(1+exp(-(mu.p7.12 + eps.pA[t])))
      p7.12M.prob[t] <- 1/(1+exp(-(mu.p7.12M + eps.pAM[t])))

      pA.prob[t] <- 1/(1+exp(-(mu.pA + eps.pA[t])))
      pAM.prob[t] <- 1/(1+exp(-(mu.pAM + eps.pAM[t])))

      phiP.prob[t] <- 1/(1+exp(-(mu.P + epsP[t])))
      phiPM.prob[t] <- 1/(1+exp(-(mu.PM + epsP[t])))
      phi1.prob[t] <- 1/(1+exp(-(mu.1 + eps1[t])))
      phi1M.prob[t] <- 1/(1+exp(-(mu.1M + eps1[t])))
      phi2.3.prob[t] <- 1/(1+exp(-(mu.2.3 + eps2.3[t])))
      phi2.3M.prob[t] <- 1/(1+exp(-(mu.2.3M + eps2.3[t])))
      
      phi4.6.prob[t] <- 1/(1+exp(-(mu.4.6 + eps4.6[t])))
      phi4.6M.prob[t] <- 1/(1+exp(-(mu.4.6M + eps4.6M[t])))
      
      phi7.9.prob[t] <- 1/(1+exp(-(mu.7.9 + eps7.9[t])))
      phi7.9M.prob[t] <- 1/(1+exp(-(mu.7.9M + eps7.9M[t])))
      
      phi10.12.prob[t] <- 1/(1+exp(-(mu.10.12 + epsA[t])))
      phi10.12M.prob[t] <- 1/(1+exp(-(mu.10.12M + epsAM[t])))
      
      phi13.16.prob[t] <- 1/(1+exp(-(mu.13.16 + epsA[t])))
      phi13.16M.prob[t] <- 1/(1+exp(-(mu.13.16M + epsAM[t])))

      phiA.prob[t] <- 1/(1+exp(-(mu.A + epsA[t])))
      phiAM.prob[t] <- 1/(1+exp(-(mu.AM + epsAM[t])))
}

    
    #likelihood
for (i in 1:n_f) { #females
    z[i, fc[i]:fc[i]] <- 1 #pups at first capture

for (t in (fc[i] + 1):n_occasions) {
      z[i,t] ~ dcat(state_probs[i,t-1,1:19])
      y[i,t] ~ dcat(event_probs[i,t,1:19])
      
    state_probs[i,t-1,1:19] <- getPHI(z = z[i,t-1], 
                                      phiP = phiP[i,t-1], phi1 = phi1[i,t-1], phi2 = phi2[i,t-1], 
                                      phi3 = phi3[i,t-1], phi4 = phi4[i,t-1], phi5 = phi5[i,t-1], 
                                      phi6 = phi6[i,t-1], phi7 = phi7[i,t-1], phi8 = phi8[i,t-1],
                                      phi9 = phi9[i,t-1], phi10 = phi10[i,t-1], 
                                      phi11 = phi11[i,t-1], phi12 = phi12[i,t-1],
                                      phi13 = phi13[i,t-1], phi14 = phi14[i,t-1], 
                                      phi15 = phi15[i,t-1], phi16 = phi16[i,t-1],
                                      phiA = phiA[i,t-1])
    
    event_probs[i,t,1:19] <- getP(z = z[i,t], 
                                    p1 = p1[i,t-1], p2 = p2[i,t-1], p3 = p3[i,t-1], 
                                    p4 = p4[i,t-1], p5 = p5[i,t-1], p6 = p6[i,t-1],
                                    p7 = p7[i,t-1], p8 = p8[i,t-1], p9 = p9[i,t-1],
                                  p10 = p10[i,t-1], p11 = p11[i,t-1], p12 = p12[i,t-1],
                                  p13 = p13[i,t-1], p14 = p14[i,t-1], p15 = p15[i,t-1],
                                    p16 = p16[i,t-1], pA = pA[i,t-1])
    } #t likelihood 
} #i likelihood 
    
    for (i in 1:n_m) { #males
    zm[i, fc_m[i]:fc_m[i]] <- 1 #pups at first capture

for (t in (fc_m[i] + 1):n_occasions) {
      zm[i,t] ~ dcat(state_probsM[i,t-1,1:19])
      ym[i,t] ~ dcat(event_probsM[i,t,1:19])
      
    state_probsM[i,t-1,1:19] <- getPHI(z = zm[i,t-1], 
                                      phiP = phiPM[i,t-1], phi1 = phi1M[i,t-1], 
                                      phi2 = phi2M[i,t-1], 
                                      phi3 = phi3M[i,t-1], 
                                      phi4 = phi4M[i,t-1], phi5 = phi5M[i,t-1], 
                                      phi6 = phi6M[i,t-1], phi7 = phi7M[i,t-1], 
                                      phi8 = phi8M[i,t-1], phiA = phiAM[i,t-1],
                                      phi9 = phi9M[i,t-1], phi10 = phi10M[i,t-1],
                                      phi11 = phi11M[i,t-1], phi12 = phi12M[i,t-1],
                                      phi13 = phi13M[i,t-1], phi14 = phi14M[i,t-1],
                                      phi15 = phi15M[i,t-1], phi16 = phi16M[i,t-1])
    
    event_probsM[i,t,1:19] <- getP(z = zm[i,t], 
                                    p1 = p1M[i,t-1], p2 = p2M[i,t-1], p3 = p3M[i,t-1], 
                                    p4 = p4M[i,t-1], p5 = p5M[i,t-1], p6 = p6M[i,t-1],
                                    p7 = p7M[i,t-1], p8 = p8M[i,t-1], p9 = p9M[i,t-1],
                                    p10 = p10M[i,t-1], p11 = p11M[i,t-1], p12 = p12M[i,t-1], 
                                  p13 = p13M[i,t-1],
                                  p14 = p14M[i,t-1], p15 = p15M[i,t-1], p16 = p16M[i,t-1], 
                                  pA = pAM[i,t-1])
    } #t likelihood 
} #i likelihood 
    
}) # mod   

##### run model ####
nim.data <- list(y = y, ym = ym)

nim.constants <- list(n_f = dim(y)[1], n_m = dim(ym)[1], 
                      n_occasions = n_occasions,
                      mass_f = mass_f, mass_m = mass_m, #site = rook, sex = sex,
                      fc = fc, fc_m = fc_m)

inits <- list(int.phiP = 0.9, int.phi1 = 0.9, int.phi2.3 = 0.9, int.phi4.6 = 0.9, int.phi7.9 = 0.9, 
              int.phiA = 0.9, 
              int.phiPM = 0.9, int.phi1M = 0.9, int.phi2.3M = 0.9, int.phi4.6M = 0.9, int.phi7.9M = 0.9, 
              int.phiAM = 0.9,
              int.p1 = 0.5, int.p2.3 = 0.9, int.p4.6 = 0.9, int.p4.6M = 0.9, int.p7.12 = 0.5, 
              int.p7.12M = 0.5, int.pA = 0.9, int.pAM = 0.9,
              # mu.p1 = qlogis(0.7), mu.p2 = qlogis(0.6), mu.p3 = qlogis(0.6),
              # mu.pJ = qlogis(0.6), mu.pA = qlogis(0.6),
              b.massP = 0, b.mass1 = 0, b.massPM = 0, b.mass1M = 0,
              z = z.init, zm = z.init.m)

### parameters
params <- c('int.p1', 'int.p2.3', 'int.p4.6', 'int.p7.12', 'int.pA', 'int.p4.6M', 
            'int.p7.12M', 'int.pAM',
            'p1.prob', 'p2.3.prob', 'p4.6.prob', 'p4.6M.prob', 'p7.12.prob', 'p7.12M.prob', 'pA.prob', 'pAM.prob',

            'phiP.prob', 'phi1.prob', 'phi2.3.prob', 'phi4.6.prob', 'phi7.9.prob', 'phi10.12.prob',
            'phi13.16.prob', 'phiA.prob',
            
            'phiPM.prob', 'phi1M.prob', 'phi2.3M.prob', 'phi4.6M.prob', 'phi7.9M.prob', 'phi10.12M.prob',
            'phi13.16M.prob', 'phiAM.prob',
            
            'b.massP', 'b.mass1', 'b.massPM', 'b.mass1M',
 
            'epsP', 'eps1', 'eps2.3', 'eps4.6', 'eps7.9', 'epsA', 'epsAM',
           
            'int.phiP', 'int.phi1', 'int.phi2.3', 'int.phi4.6', 'int.phi7.9',
            'int.phi10.12', 'int.phi13.16', 'int.phiA',
            'int.phiPM', 'int.phi1M', 'int.phi2.3M', 'int.phi4.6M', 'int.phi7.9M',
            'int.phi10.12M', 'int.phi13.16M', 'int.phiAM')

### run model
# n.iter = 3500; n.chains = 3; n.burnin = 2000; nthin = 3; nAdapt = 20
n.iter = 15000; n.chains = 3; n.burnin = 8000; nthin = 3; nAdapt = 20
n.iter = 1000; n.chains = 2; n.burnin = 400; nthin = 2; nAdapt = 20


start <- Sys.time()

cores=detectCores() 
used.cores = min(n.chains, cores) 
cl <- makeCluster(n.chains, setup_strategy = "sequential") 
registerDoParallel(cl) 

foreach(i = 1:n.chains) %dopar% { 
  library(nimble)
  library(here)
  source(here("scripts", "nimbleFunctions.R"))

Rmodel <- nimbleModel(code = CSL_CJS, 
                      constants = nim.constants, data = nim.data, 
                      calculate = F, check = F, inits = inits)

conf <- configureMCMC(Rmodel, monitors = params, control = list(adaptInterval = nAdapt), 
                      thin = nthin, useConjugacy = FALSE)

Rmcmc <- buildMCMC(conf)  #produce uncompiled R mcmc function
Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)

out <- runMCMC(Cmcmc, niter = n.iter, nburnin = n.burnin, 
               # nchains = n.chains, 
               nchains = 1,
               inits = inits,
                 setSeed = FALSE, progressBar = TRUE,
               samplesAsCodaMCMC = TRUE)


  saveRDS(out, here('results', paste("out.parallel_RE_", i, ".RDS", sep = ""))) 
  
} # closes parallel loop

out_1 <- readRDS(here::here('results', paste("out.parallel_RE_", "1.RDS", sep = "")))
out_2 <- readRDS(here::here('results', paste("out.parallel_RE_", "2.RDS", sep = "")))
out_3 <- readRDS(here::here('results', paste("out.parallel_RE_", "3.RDS", sep = "")))

library(coda)
out <- list(`out_1`, `out_2`, `out_3`) %>% as.mcmc.list()

# saveRDS(out, here::here('results', 'out_RE.RDS'))

```


```{r null model HMM}

####

HMM_code <- nimbleCode({
  
   for (i in 1:n_f) { 
    for (t in 1:(n_occasions - 1)) {
      logit(phiP[i,t]) <- mu.P + 
        b.sst.P*sst_pupForage[t] #+
        #b.massP*mass_f[i] #+ epsP[t] + b.siteP[site[i]]
      logit(p1[i,t]) <- mu.p1 #+ eps.p1[t]
    } #t 
    
    for (t in 2:(n_occasions-1)) {
      logit(phi1[i,t]) <- mu.1 + 
        b.sst.np*sst_np[t] #+
        # b.mass1*mass_f[i] #+ eps1[t] + b.site1[site[i]]
      logit(p2[i,t]) <- mu.p2.3  #+ eps.p2[t]
    }
    
    for (t in 3:(n_occasions-1)) {
      logit(phi2[i,t]) <- mu.2.3 + 
        b.sst.np*sst_np[t] #+ eps2[t] + b.site2[site[i]]
      logit(p3[i,t]) <- mu.p2.3 #+ eps.pJ[t]
    }
    
    for (t in 4:(n_occasions-1)) { 
      logit(phi3[i,t]) <- mu.2.3 + 
        b.sst.np*sst_np[t] #+ epsJ[t] + b.siteJ[site[i]]
      logit(p4[i,t]) <- mu.p4.6 #+ eps.pJ[t]
    } #t psi
    
    for (t in 5:(n_occasions-1)) {
      logit(phi4[i,t]) <- mu.4.6 #+ epsJ[t] + b.siteJ[site[i]]
      logit(p5[i,t]) <- mu.p4.6 #+ eps.pA[t]
    } #t 
    
    for (t in 6:(n_occasions-1)) {  
      logit(phi5[i,t]) <- mu.4.6 #+ epsA[t] 
      logit(p6[i,t]) <- mu.p4.6 #+ eps.pA[t]
    } #t 
    
    for (t in 7:(n_occasions-1)) {  
      logit(phi6[i,t]) <- mu.4.6 #+ epsA[t] 
      logit(p7[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t 
    
    for (t in 8:(n_occasions-1)) {  
      logit(phi7[i,t]) <- mu.7.9 #+ epsA[t] 
      logit(p8[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t 
    
    for (t in 9:(n_occasions-1)) {  
      logit(phi8[i,t]) <- mu.7.9 #+ epsA[t] 
      logit(p9[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t 
    
    for (t in 10:(n_occasions-1)) {  
      logit(phi9[i,t]) <- mu.7.9 #+ epsA[t] 
      logit(p10[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t 
    
    for (t in 11:(n_occasions-1)) {  
      logit(phi10[i,t]) <- mu.10.12 # + epsA[t] 
      logit(p11[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t 
  
    for (t in 12:(n_occasions-1)) {  
      logit(phi11[i,t]) <- mu.10.12 # + epsA[t] 
      logit(p12[i,t]) <- mu.p7.12 #+ eps.pA[t]
    } #t   
    
        for (t in 13:(n_occasions-1)) {  
      logit(phi12[i,t]) <- mu.10.12 # + epsA[t] 
      logit(pA[i,t]) <- mu.pA #+ eps.pA[t]
    } #t  
    
        for (t in 14:(n_occasions-1)) {  
      logit(phi13[i,t]) <- mu.13.16 # + epsA[t] 
    } #t  
    
        for (t in 15:(n_occasions-1)) {  
      logit(phi14[i,t]) <- mu.13.16 # + epsA[t] 
    } #t  
    
        for (t in 16:(n_occasions-1)) {  
      logit(phi15[i,t]) <- mu.13.16 # + epsA[t] 
    } #t  
    
        for (t in 17:(n_occasions-1)) {  
      logit(phi16[i,t]) <- mu.13.16 # + epsA[t] 
    } #t  
    
        for (t in 18:(n_occasions-1)) {  
      logit(phiA[i,t]) <- mu.A # + epsA[t] 
    } #t  
  } #females
  
  
### Priors
    #p
    mu.p1 <- log(int.p1/(1 - int.p1))
    mu.p2.3 <- log(int.p2.3/(1 - int.p2.3))
    mu.p4.6 <- log(int.p4.6/(1 - int.p4.6))
    mu.p7.12 <- log(int.p7.12/(1 - int.p7.12))
    # mu.p13.16 <- log(int.p13.16/(1 - int.p13.16))
    mu.pA <- log(int.pA/(1 - int.pA))

    int.p1 ~ dunif(0,1)
    int.p2.3 ~ dunif(0,1)
    int.p4.6 ~ dunif(0,1)
    int.p7.12 ~ dunif(0,1)
    # int.p13.16 ~ dunif(0,1)
    int.pA ~ dunif(0,1)

    #survival
    mu.P <- log(int.phiP/(1 - int.phiP))
    mu.1 <- log(int.phi1/(1 - int.phi1))
    mu.2.3 <- log(int.phi2.3/(1 - int.phi2.3))
    mu.4.6 <- log(int.phi4.6/(1 - int.phi4.6))
    mu.7.9 <- log(int.phi7.9/(1 - int.phi7.9))
    mu.10.12 <- log(int.phi10.12/(1 - int.phi10.12))
    mu.13.16 <- log(int.phi13.16/(1 - int.phi13.16))
    mu.A <- log(int.phiA/(1 - int.phiA))
    
    int.phiP ~ dunif(0,1)
    int.phi1 ~ dunif(0,1)
    int.phi2.3 ~ dunif(0,1)
    int.phi4.6 ~ dunif(0,1)
    int.phi7.9 ~ dunif(0,1)
    int.phi10.12 ~ dunif(0,1)
    int.phi13.16 ~ dunif(0,1)
    int.phiA ~ dunif(0,1)
    
    b.massP ~ dnorm(0, sd = s.mass)
    b.mass1 ~ dnorm(0, sd = s.mass)
    # b.massPM ~ dnorm(0, sd = s.mass)
    # b.mass1M ~ dnorm(0, sd = s.mass)
    s.mass ~ dexp(1)
  
  b.sst.P ~ dnorm(0, sd = 1)
  b.sst.1 ~ dnorm(0, sd = 1)
  # b.sst.A ~ dnorm(0, sd = 1)
  
  #likelihood
  for (i in 1:n.ind) {
    y[i,fc[i]:n.occ] ~ dDHMMo(init = init[1:19], 
                        probObs = obs[i,1:n.state, 1:n.obs,fc[i]:n.occ],
                        probTrans = state[i,1:n.state, 1:n.state, fc[i]:(n.occ-1)],
                        len = length(fc[i]:n.occ), checkRowSums = T)
  }
  
  #define transition matrices and initial state probabilities
  for (i in 1:n.ind) {
  for (t in fc[i]:(n.occ-1)) {

    state[i,1,1:19,t] <- c(0,phiP[i,t],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-phiP[i,t])  #pup
    state[i,2,1:19,t] <- c(0,0,phi1[i,t],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-phi1[i,t])  #yearling   
    state[i,3,1:19,t] <- c(0,0,0,phi2[i,t],0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-phi2[i,t])  #2yr
    state[i,4,1:19,t] <- c(0,0,0,0,phi3[i,t],0,0,0,0,0,0,0,0,0,0,0,0,0,1-phi3[i,t])  #3yr 
    state[i,5,1:19,t] <- c(0,0,0,0,0,phi4[i,t],0,0,0,0,0,0,0,0,0,0,0,0,1-phi4[i,t])  #4yr
    state[i,6,1:19,t] <- c(0,0,0,0,0,0,phi5[i,t],0,0,0,0,0,0,0,0,0,0,0,1-phi5[i,t])  #5yr           
    state[i,7,1:19,t] <- c(0,0,0,0,0,0,0,phi6[i,t],0,0,0,0,0,0,0,0,0,0,1-phi6[i,t])  #6yr 
    state[i,8,1:19,t] <- c(0,0,0,0,0,0,0,0,phi7[i,t],0,0,0,0,0,0,0,0,0,1-phi7[i,t])       
    state[i,9,1:19,t] <- c(0,0,0,0,0,0,0,0,0,phi8[i,t],0,0,0,0,0,0,0,0,1-phi8[i,t])       
    state[i,10,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,phi9[i,t],0,0,0,0,0,0,0,1-phi9[i,t])   
    state[i,11,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,phi10[i,t],0,0,0,0,0,0,1-phi10[i,t]) 
    state[i,12,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,phi11[i,t],0,0,0,0,0,1-phi11[i,t]) 
    state[i,13,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,phi12[i,t],0,0,0,0,1-phi12[i,t]) 
    state[i,14,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,phi13[i,t],0,0,0,1-phi13[i,t]) 
    state[i,15,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,phi14[i,t],0,0,1-phi14[i,t]) 
    state[i,16,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,phi15[i,t],0,1-phi15[i,t]) 
    state[i,17,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,phi16[i,t],1-phi16[i,t]) 
    state[i,18,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,phiA[i,t],1-phiA[i,t])       
    state[i,19,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1) #D
  }
  }
  
  init[1:19] <- c(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
  
  for (i in 1:n.ind) {
  for (t in 1:n.occ) {

  obs[i,1,1:19,t] <- c(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0) #pups seen as pups
  obs[i,2,1:19,t] <- c(0,p1[i,t],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-p1[i,t])   #1yr      
  obs[i,3,1:19,t] <- c(0,0,p2[i,t],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-p2[i,t])   #2yr
  obs[i,4,1:19,t] <- c(0,0,0,p3[i,t],0,0,0,0,0,0,0,0,0,0,0,0,0,0,1-p3[i,t])   #3yr
  obs[i,5,1:19,t] <- c(0,0,0,0,p4[i,t],0,0,0,0,0,0,0,0,0,0,0,0,0,1-p4[i,t])   #4yr 
  obs[i,6,1:19,t] <- c(0,0,0,0,0,p5[i,t],0,0,0,0,0,0,0,0,0,0,0,0,1-p5[i,t])   #5yr           
  obs[i,7,1:19,t] <- c(0,0,0,0,0,0,p6[i,t],0,0,0,0,0,0,0,0,0,0,0,1-p6[i,t])   #6yr  
  obs[i,8,1:19,t] <- c(0,0,0,0,0,0,0,p7[i,t],0,0,0,0,0,0,0,0,0,0,1-p7[i,t])   #7yr  
  obs[i,9,1:19,t] <- c(0,0,0,0,0,0,0,0,p8[i,t],0,0,0,0,0,0,0,0,0,1-p8[i,t])   #8yr  
  obs[i,10,1:19,t] <- c(0,0,0,0,0,0,0,0,0,p9[i,t],0,0,0,0,0,0,0,0,1-p9[i,t])   #9yr  
  obs[i,11,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,p10[i,t],0,0,0,0,0,0,0,1-p10[i,t])   #9yr
  obs[i,12,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,p11[i,t],0,0,0,0,0,0,1-p11[i,t])   #9yr
  obs[i,13,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,p12[i,t],0,0,0,0,0,1-p12[i,t])   #9yr
  obs[i,14,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,p13[i,t],0,0,0,0,1-p13[i,t])   #9yr
  obs[i,15,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,p14[i,t],0,0,0,1-p14[i,t])   #9yr
  obs[i,16,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,p15[i,t],0,0,1-p15[i,t])   #9yr
  obs[i,17,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,p16[i,t],0,1-p16[i,t])   #9yr
  obs[i,18,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,pA[i,t],1-pA[i,t])   #pA
  obs[i,19,1:19,t] <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1)      #nd
  }
  }
  
}) #mod

constants <- list(n.ind = dim(y)[1], n_f = dim(y)[1],
                  n.state = max(y, na.rm = T), n.obs = max(ch, na.rm = T),
                  fc = fc,
                  mass_f = as.numeric(mass_f),
                  sst_pupForage = sst_dat[,2],
                  sst_pupGest = sst_dat[,3],
                  sst_np = sst_dat[,4],
                  n.occ = dim(y)[2],
                  n_occasions = dim(y)[2])

# params <- c('mean.p1', 'mean.p2', 'mean.p3', 'mean.p4', 'mean.pB', 'mean.pNB',
#             "mu.psi3", 'mu.psi4', 'mu.psiB', 'mu.psiNB',
#             'int.p1', 'int.p2', 'int.p3', 'int.p4', 'int.pB', 'int.pNB', 
#            'int.psi3', 'int.psi4', 'int.psiB', 'int.psiNB',
#            'int.phi1', 'int.phi2', 'int.phi3', 'int.phi4', 'int.phiB', 'int.phiNB',
#            'eps1', 'epsJ', 'epsB', 'eps.psiB',
#             #covariates
#             'b.mass', 'b.mass.psi',
#             'b.delB', 'p.delB')

nb <- 4000; ni <- 9000; nt <- 2; nc <- 2; nAdapt = 20
# nb <- 10000; ni <- 22000; nt <- 2; nc <- 3; nAdapt = 20


#build
HMM_mod <- nimbleModel(HMM_code,
                       constants = constants,
                       data = list(y = ch),
                       inits = list(int.phiB = 0.9))

# HMM_conf <- configureMCMC(HMM_mod, monitors = params, control = list(adaptInterval = nAdapt), 
#                       thin = nt, useConjugacy = FALSE, enableWAIC = TRUE)
# 
# #compile
# HMM_mcmc <- buildMCMC(HMM_conf)
# Cmodel <- compileNimble(HMM_mod)
# Cmcmc <- compileNimble(HMM_mcmc, project = HMM_mod)

##no custom params
#compile
HMM_mcmc <- buildMCMC(HMM_mod)
Cmodel <- compileNimble(HMM_mod)
Cmcmc <- compileNimble(HMM_mcmc, project = HMM_mod)

#run
out <- runMCMC(Cmcmc, niter = ni, nburnin = nb, thin = nt, 
               # nchains = 1,
               nchains = nc,
               samplesAsCodaMCMC = T)

save(out, file = here('results', 'HMM', 'out_dDHMMo_sst.RData'))

# save(out, file = here('results', 'HMM', 'out_dDHMMo_null.RData'))

```


```{r load results and diagnostics}


out <- readRDS(here::here('results', 'out_ME.RDS'))
# out <- list(out$samples$chain1, out$samples$chain2, out$samples$chain3) %>% as.mcmc.list()
# out <- list(out$chain1, out$chain2, out$chain3) %>% as.mcmc.list()


all_pars <- colnames(out[[1]])
noZ <- all_pars[which(!grepl('z', all_pars))]

# posts <- out[,noZ]
outmat <- as.matrix(out)

plot(out[,c('int.phiP', 'int.phi1', 'int.phi2.3', 'int.phi4.6', 'int.phiA')])

plot(out[,c('b.sexP[1]', 'b.sex1[1]', 'b.sex2[1]', 'b.sexJ[1]', 'b.sexA[1]')])
plot(out[,c('b.siteP[2]', 'b.site1[2]', 'b.site2[2]', 'b.siteJ[2]', 'b.siteA[2]')])

post_sum <- data.frame(
  med = apply(outmat, 2, function(x) quantile(x, probs = 0.5, na.rm = T, names = F)),
  lower = apply(outmat, 2, function(x) quantile(x, probs = 0.025, na.rm = T, names = F)),
  upper = apply(outmat, 2, function(x) quantile(x, probs = 0.975, na.rm = T, names = F)))
post_sum$variable <- row.names(post_sum)

```

###Just for looking after model runs, don't update figures!
```{r mean phi by sex}

#mean rates
sex.pars <- all_pars[which(grepl('b.sex', all_pars))]
mu.pars <- all_pars[which(grepl('mu.', all_pars))]

pars <- c(sex.pars, mu.pars)

mu.vals <- post_sum %>%
  filter(variable %in% mu.pars) %>%
  transform(age = gsub('mu.', '', variable)) 

b.sex <- post_sum %>% filter(grepl('b.sex', variable) & med != 0) %>%
  transform(age = ifelse(grepl('sexP', variable), 'P', 
                         ifelse(grepl('sex1', variable), '1',
                                ifelse(grepl('sex2', variable), '2', 
                                       ifelse(grepl('sex3', variable), '3', 
                                              ifelse(grepl('sexJ', variable), 'J', 'A'))))))

#Female back transformed values
mean.phi.sex.vals <- mu.vals %>%
  merge(b.sex, by = 'age', suffixes = c('', '.sex'), all = T) %>%
  #fill b.sex for older age intercepts
  # transform(med.sex = ifelse(is.na(med.sex), b.sex[b.sex$age == 'A', 'med'], med.sex),
  #           lower.sex = ifelse(is.na(lower.sex), b.sex[b.sex$age == 'A', 'lower'], lower.sex),
  #           upper.sex = ifelse(is.na(upper.sex), b.sex[b.sex$age == 'A', 'upper'], upper.sex)) %>%
  transform(med = 1/(1+exp(-(med + med.sex))),
            lower = 1/(1+exp(-(lower + lower.sex))),
            upper = 1/(1+exp(-(upper + upper.sex)))) %>%
  transform(sex = 'Female') %>%
  dplyr::select(c(med, lower, upper, variable, age, sex)) %>%
  bind_rows(
    post_sum %>%
  filter(grepl('int.phi', variable)) %>%
  transform(age = gsub('int.phi', '', variable), sex = 'Male')) %>%
  transform(age = factor(age, levels = c('P', '1', '2', '3', 'J', 'A'),
                         labels = c('P', '1', '2', '3', 'J', 'A'))) 

ggplot(mean.phi.sex.vals, aes(age, med, col = sex, group = sex)) +
  geom_point(position = position_dodge(0.5)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.5, position = position_dodge(0.5)) +
  xlab('') + ylab(expression(paste('Predicted survival probability ',  '(', phi, ')'))) +
  ggtitle('') +
  plot_theme(legend.position = 'top', panel.border = element_rect(fill = NA),
             plot.title = element_text(hjust = 0.5)) +
  guides(color = guide_legend("", nrow = 1, byrow = T)) +
  scale_color_manual(values = rainbow2[c(2,5)], name = '') 

```


