---
title: "CSL empirical estimates - spring 2025"
output: html_document
---

```{r setup, include=FALSE, fig.align = 'center'}

knitr::opts_chunk$set(echo = FALSE, eval = T, message = F, warning = F, fig.align = 'center')

library(here) #v1.0.1
library(dplyr) #v1.0.5
# library(nimble) #v0.12.1
library(ggplot2)
library(coda)
library(ggh4x)
library(readr)
library(knitr)
library(Hmisc)
library(stringr)

source(here::here('scripts', 'PlotTheme.R'))

```


```{r vital rates}

out <- readRDS(here::here('results', 'out_sst.RDS'))

all_pars <- colnames(out[[1]])
outmat <- as.matrix(out)

post_sum <- data.frame(
  med = apply(outmat, 2, function(x) quantile(x, probs = 0.5, na.rm = T, names = F)),
  lower = apply(outmat, 2, function(x) quantile(x, probs = 0.025, na.rm = T, names = F)),
  upper = apply(outmat, 2, function(x) quantile(x, probs = 0.975, na.rm = T, names = F)))
post_sum$variable <- row.names(post_sum)

#mean rates
# sex.pars <- all_pars[which(grepl('b.sex', all_pars))]
mu.pars <- all_pars[which(grepl('mu.', all_pars))]

# b.mass_sum <- post_sum %>% filter(grepl('b.mass', variable)) %>%
#   # transform(var_name = ifelse(grepl('b.mass.f', variable), '1', 
#   #                                    ifelse(grepl('b.mass.m', variable), '1M',
#                   transform(var_name = ifelse(grepl('b.mass1', variable), '1', 
#                        ifelse(grepl('b.massP', variable), 'P', NA))) %>%
#   transform(sex = ifelse(grepl('M', variable), 'M', 'F')) %>%
#   transform(var_name = factor(var_name, levels = c('P', '1'))) 
#   
# ggplot(b.mass_sum,
#        aes(x = var_name, y = med, col = sex, group = sex)) +
#   geom_errorbar(aes(x = var_name, ymin=lower, ymax=upper),
#                 position = position_dodge(0.5),
#                 width = 0.25, show.legend = F) +
#   geom_point(size = 0.8, position = position_dodge(0.5)) +
#   geom_hline(aes(yintercept = 0), linetype = 'dashed') +
#   xlab('Age class') + ylab(expression(paste('Logit-scale effect of handling mass'))) +
#   ggtitle('') +
#   plot_theme(legend.position = 'top', panel.border = element_rect(fill = NA),
#              plot.title = element_text(hjust = 0.5)) +
#   scale_color_manual(values = rainbow2[c(2,5,6,7,8)], name = 'Sex')


#survival
int_dat <- post_sum %>% filter(grepl('int.phi', variable)) %>%
  # bind_rows(post_sum %>% filter(grepl('int.psi', variable))) %>%
  transform(variable = gsub('int.', '', variable)) %>%
  transform(sex = ifelse(grepl('M', variable), 'M', 'F')) %>%
  transform(age = gsub('phi', '', variable)) %>%
  transform(age = gsub('M', '', age)) %>%
   transform(age = factor(age, levels = c('P', 'PM', '1', 
                                                   '1M', '2.3', '2.3M',
                            '4.6', '4.6M', '7.9', '7.9M', '10.12', '10.12M',
                            '13.16', '13.16M', 'A', 'AM'))) 
  
  
phi_plot <- ggplot(int_dat %>% filter(grepl('phi', variable)),
       aes(age, med, color = sex)) +
  geom_errorbar(aes(x = age, ymin=lower, ymax=upper),
                position = position_dodge(0.5),
                width = 0.35) +
  geom_point(size = 0.8, position = position_dodge(0.5)) +
  xlab('Age class') + ylab(expression(paste('Survival probability ',  '(', phi, ')'))) +
  ggtitle('') +
  # facet_wrap(~sex, scales = 'free_x', drop = T) +
  plot_theme(legend.position = 'top', 
             panel.border = element_rect(fill = NA),
             plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = c('black', 'darkgrey'), name = 'Sex')
  # scale_color_manual(values = rainbow2[c(2,6,7,8)], name = 'Sex')

#fecundity
fec_dat <- post_sum %>% filter(grepl('int.fec', variable)) %>%
  # bind_rows(post_sum %>% filter(grepl('int.psi', variable))) %>%
  transform(variable = ifelse(grepl('low', variable), 'Fec_low', 'Fec_high')) %>%
   transform(age = factor(variable, levels = c('Fec_low', 'Fec_high'),
                          labels = c('4:9', '10:22'))) 

fec_plot <- ggplot(fec_dat, aes(x = age, y = value)) +
  geom_errorbar(aes(x = age, ymin=lower, ymax=upper),
                position = position_dodge(0.5),
                width = 0.35) +
  geom_point(size = 0.8, position = position_dodge(0.5)) +
  xlab('Fecundity age bins') + ylab(expression(paste('Fecundity ',  '(', f, ')'))) +
  ggtitle('') +
  # facet_wrap(~sex, scales = 'free_x', drop = T) +
  plot_theme(legend.position = 'top', 
             panel.border = element_rect(fill = NA),
             plot.title = element_text(hjust = 0.5))

#detection
int_dat <- post_sum %>% filter(grepl('int.p', variable)) %>%
  # bind_rows(post_sum %>% filter(grepl('int.psi', variable))) %>%
  transform(variable = gsub('int.', '', variable)) %>%
  filter(!grepl('phi', variable)) %>%
    transform(sex = ifelse(grepl('M', variable), 'M', 'F')) %>%
  transform(age = gsub('p', '', variable)) %>%
  transform(age = gsub('M', '', age)) %>%
    transform(age = factor(age, levels = c('1', '2.3', '4.6',  
                                                   '7.12', 'A'))) 

p_plot <- ggplot(int_dat,
       aes(age, med, color = sex)) +
  geom_errorbar(aes(x = age, ymin=lower, ymax=upper),
                position = position_dodge(0.5),
                width = 0.25) +
  geom_point(size = 0.8, position = position_dodge(0.5)) +
  xlab('Age class') + ylab(expression(paste('Detection probability ',  '(', p, ')'))) +
  ggtitle('') +
  # facet_wrap(~sex, scales = 'free_x', drop = T) +
  plot_theme(legend.position = 'top', 
             panel.border = element_rect(fill = NA),
             plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = c('black', 'darkgrey'), name = 'Sex')
  # scale_color_manual(values = rainbow2[c(2,6,7,8)], name = 'Sex')




```

```{r covariate effects and predictions}

#sst
b.sst_sum <- post_sum %>% filter(grepl('b.sst', variable)) %>%
  # transform(var_name = ifelse(grepl('b.mass.f', variable), '1', 
  #                                    ifelse(grepl('b.mass.m', variable), '1M',
                  transform(var_name = gsub('b.sst.', '', variable)) %>%

sst_eff_plot <- ggplot(b.sst_sum, aes(x = var_name, y = med)) +
  geom_errorbar(aes(x = var_name, ymin=lower, ymax=upper),
                position = position_dodge(0.5),
                width = 0.25, show.legend = F) +
  geom_point(size = 0.8, position = position_dodge(0.5)) +
  geom_hline(aes(yintercept = 0), linetype = 'dashed') +
  xlab('Age class') + ylab(expression(paste('Logit-scale effect of SST'))) +
  ggtitle('') +
  pres_theme(legend.position = 'top', #panel.border = element_rect(fill = NA),
             plot.title = element_text(hjust = 0.5))

#changes in survival from sst
## sequence of values
sst_seq <- seq(min(sst_dat[,2]), max(sst_dat[,2]), length.out = 100)
sst_np_seq <- seq(min(sst_dat[,4]), max(sst_dat[,4]), length.out = 100)

# back-transform a single MCMC row across the sequence
get_pred <- function(phi, b_sst, sequence) {
  mu <- plogis(phi)
  logit_p <- mu + b_sst*sequence
  return(1 / (1 + exp(-logit_p)))
}

samples <- as.matrix(out)
#pups
preds_p <- apply(samples, 1, function(s) {
  get_pred(s["int.phiP"], s["b.sst.P"], sst_seq)
})

preds_pm <- apply(samples, 1, function(s) {
  get_pred(s["int.phiPM"], s["b.sst.P"], sst_seq)
})

preds_1 <- apply(samples, 1, function(s) {
  get_pred(s["int.phi1"], s["b.sst.1"], sst_seq)
})

preds_1m <- apply(samples, 1, function(s) {
  get_pred(s["int.phi1M"], s["b.sst.1"], sst_seq)
})

preds_2.3 <- apply(samples, 1, function(s) {
  get_pred(s["int.phi2.3"], s["b.sst.2.3"], sst_seq)
})

preds_2.3m <- apply(samples, 1, function(s) {
  get_pred(s["int.phi2.3M"], s["b.sst.2.3M"], sst_seq)
})

preds_4.6 <- apply(samples, 1, function(s) {
  get_pred(s["int.phi4.6"], s["b.sst.4.6"], sst_seq)
})

# preds_4.6m <- apply(samples, 1, function(s) {
#   get_pred(s["int.phi4.6M"], s["b.sst.4.6M"], sst_seq)
# })

preds_7.9 <- apply(samples, 1, function(s) {
  get_pred(s["int.phi7.9"], s["b.sst.7.9"], sst_seq)
})

# preds_7.9m <- apply(samples, 1, function(s) {
#   get_pred(s["int.phi7.9M"], s["b.sst.7.9M"], sst_seq)
# })

preds_10.12 <- apply(samples, 1, function(s) {
  get_pred(s["int.phi10.12"], s["b.sst.A"], sst_seq)
})

preds_13.16 <- apply(samples, 1, function(s) {
  get_pred(s["int.phi13.16"], s["b.sst.A"], sst_seq)
})

preds_A <- apply(samples, 1, function(s) {
  get_pred(s["int.phiA"], s["b.sst.A"], sst_seq)
})

summarize_preds_pup <- function(pred_matrix) {
  data.frame(
    sst_val = sst_seq,
    val = 1:length(sst_seq),
    mean_phi = rowMeans(pred_matrix),
    low_phi  = apply(pred_matrix, 1, quantile, probs = 0.025),
    high_phi = apply(pred_matrix, 1, quantile, probs = 0.975))
}

summarize_preds_np <- function(pred_matrix) {
  data.frame(
    sst_val = sst_np_seq,
    val = 1:length(sst_np_seq),
    mean_phi = rowMeans(pred_matrix),
    low_phi  = apply(pred_matrix, 1, quantile, probs = 0.025),
    high_phi = apply(pred_matrix, 1, quantile, probs = 0.975))
}

preds_all <- rbind(summarize_preds_pup(preds_p) %>%
                     transform(age = 'P', sex = 'Fem'),
                   summarize_preds_pup(preds_pm) %>%
                     transform(age = 'P', sex = 'Male')) %>%
  bind_rows(rbind(summarize_preds_np(preds_1) %>%
                     transform(age = '1', sex = 'Fem'),
                   summarize_preds_np(preds_1m) %>%
                     transform(age = '1', sex = 'Male'))) %>%
  # bind_rows(rbind(summarize_preds_np(preds_2.3) %>%
  #                    transform(age = '2:3', sex = 'Fem'),
  #                  summarize_preds_np(preds_2.3m) %>%
  #                    transform(age = '2:3', sex = 'Male'))) %>%
  # bind_rows(rbind(summarize_preds_np(preds_4.6) %>%
  #                    transform(age = '4:6', sex = 'Fem'),
  #                  summarize_preds_np(preds_4.6m) %>%
  #                    transform(age = '4:6', sex = 'Male'))) %>%
  bind_rows(summarize_preds_np(preds_7.9) %>%
                     transform(age = '7:9', sex = 'Fem')) %>%
  bind_rows(summarize_preds_np(preds_10.12) %>%
                     transform(age = '10:12', sex = 'Fem')) %>%
  bind_rows(summarize_preds_np(preds_13.16) %>%
                     transform(age = '13:16', sex = 'Fem')) %>%
  bind_rows(summarize_preds_np(preds_A) %>%
                     transform(age = '17+', sex = 'Fem')) %>%
  transform(age = factor(age, levels = c('P', '1', '2:3', '4:6', '7:9',
                                         '10:12', '13:16', '17+')))

sst_preds_plot <- ggplot(preds_all, aes(x = sst_val, y = mean_phi, col = sex)) +
  geom_ribbon(aes(ymin = low_phi, ymax = high_phi), alpha = 0.2, color = NA) +
  geom_line(linewidth = 1) +
  facet_grid(.~age) +
  labs(x = "SST anomalies",
       y = "Predicted survival probability") +
  theme_bw() +
  theme(legend.position = 'top',
                axis.title.x = element_text(margin = margin(t = 7))) +
  scale_y_continuous(limits = c(0, 1)) + 
  scale_color_manual(values = rainbow2[c(2,6)], name = 'Sex') + 
  scale_fill_manual(values = rainbow2[c(2,6)]) #+ 
  # scale_x_continuous(limits = c(-1.5, 2.5), breaks = c(seq(-1.5,2.5, length = 5)),
  #                    labels = round(c(seq(0.3,0.65, length = 5)),2))

```


```{r}

##calculate MNPL and OSP

#simplified approach assuming 60%, or use vital rates from IPM
# MNPL_estimates <- K_estimates * 0.60

#use vital rates from IPM
# extract MCMC matrix 
mcmc_matrix <- as.matrix(out) 

# number of posterior draws to simulate
n_draws <- 1000 
draw_indices <- sample(1:nrow(mcmc_matrix), n_draws)

# storage
K_estimates <- numeric(n_draws)
MNPL_estimates <- numeric(n_draws)
OSP_status <- numeric(n_draws)

# final year of count data to evaluate OSP status
N_current_observed <- pup_cnt_filled[35,'US_PupCnt'] 

for (i in 1:n_draws) {
  row_idx <- draw_indices[i]
  
  # extract vital rates for each MCMC draw
  mu_P   <- mcmc_matrix[row_idx, "mu.P"]
  beta_DD <- mcmc_matrix[row_idx, "beta.DD"]
  mu_1   <- mcmc_matrix[row_idx, "mu.1"]
  mu_2.3   <- mcmc_matrix[row_idx, "mu.2.3"]
  mu_4.6   <- mcmc_matrix[row_idx, "mu.4.6"]
  mu_7.9   <- mcmc_matrix[row_idx, "mu.7.9"]
  mu_10.12   <- mcmc_matrix[row_idx, "mu.10.12"]
  mu_13.16   <- mcmc_matrix[row_idx, "mu.13.16"]
  mu_A   <- mcmc_matrix[row_idx, "mu.A"]
  fec_low  <- mcmc_matrix[row_idx, "int.fec_low"]
  fec_high <- mcmc_matrix[row_idx, "int.fec_high"]
  
  # convert baseline survival to probability scale (assuming SST = 0)
  phi1 <- plogis(mu_1)
  phi2.3 <- plogis(mu_2.3)
  phi4.6 <- plogis(mu_4.6)
  phi7.9 <- plogis(mu_7.9)
  phi10.12 <- plogis(mu_10.12)
  phi13.16 <- plogis(mu_13.16)
  phiA <- plogis(mu_A)
  
  # initialize simulation arrays
  n_years <- 250 #enough time for the population to reach K
  N_history <- numeric(n_years)
  
  # start with small population to ensure the full growth curve is captured
  N_vec <- rep(5, 25) 
  
  # project forward and track the population history
  for (y in 1:n_years) {
    
    # total population (assuming equal sex ratio, multiplying female count by 2)
    N_tot <- sum(N_vec) * 2 
    N_history[y] <- N_tot
    
    # Calculate density-dependent pup survival for THIS year
    phiP_current <- plogis(mu_P - beta_DD * (N_tot / 100000))
    
    # calculate total pups born
    pups_born <- (sum(N_vec[5:10])*fec_low*0.5) + (sum(N_vec[11:23])*fec_high*0.5)
    
    # Create the next year's population vector
    N_vec_next <- numeric(25)
    N_vec_next[1] <- pups_born
    N_vec_next[2] <- N_vec[1] * phiP_current
    N_vec_next[3] <- N_vec[2] * phi1
    N_vec_next[4] <- N_vec[3] * phi2.3
    N_vec_next[5] <- N_vec[4] * phi2.3
    N_vec_next[6] <- N_vec[5] * phi4.6
    N_vec_next[7] <- N_vec[6] * phi4.6
    N_vec_next[8] <- N_vec[7] * phi4.6
    N_vec_next[9] <- N_vec[8] * phi7.9
    N_vec_next[10] <- N_vec[9] * phi7.9
    N_vec_next[11] <- N_vec[10] * phi7.9
    N_vec_next[12] <- N_vec[11] * phi10.12
    N_vec_next[13] <- N_vec[12] * phi10.12
    N_vec_next[14] <- N_vec[13] * phi10.12
    N_vec_next[15] <- N_vec[14] * phi13.16
    N_vec_next[16] <- N_vec[15] * phi13.16
    N_vec_next[17] <- N_vec[16] * phi13.16
    N_vec_next[18] <- N_vec[17] * phi13.16

    # absorbing state (ages 17-23)
    for (a in 18:24) {
      N_vec_next[a+1] <- N_vec[a] * phiA
    }
    
    # update population
    N_vec <- N_vec_next
  }
  
  # numerically derive K and MNPL
  # K is the final stabilized population size at the end of the simulation
  K_estimates[i] <- N_history[n_years]
  
  # calculate net production (the difference in population size each year)
  net_production <- diff(N_history)
  
  # find year index where net production was highest
  max_growth_year <- which.max(net_production)
  
  # MNPL is the population size at that specific peak-growth year
  MNPL_estimates[i] <- N_history[max_growth_year]
  
  # Calculate OSP ratio for this MCMC draw
  OSP_status[i] <- N_current_observed / MNPL_estimates[i]
}

cat("Carrying Capacity (K):\n",
    "Mean:", round(mean(K_estimates)), 
    "| 95% CI:", round(quantile(K_estimates, 0.025)), "-", round(quantile(K_estimates, 0.975)), "\n\n")

cat("Maximum Net Productivity Level (MNPL):\n",
    "Mean:", round(mean(MNPL_estimates)), 
    "| 95% CI:", round(quantile(MNPL_estimates, 0.025)), "-", round(quantile(MNPL_estimates, 0.975)), "\n\n")

cat("OSP Status Ratio (N_current / MNPL):\n",
    "Mean:", round(mean(OSP_status), 2), 
    "| 95% CI:", round(quantile(OSP_status, 0.025), 2), "-", round(quantile(OSP_status, 0.975), 2), "\n")

# calculate the probability that the population is within its OSP (> 1.0)
prob_in_OSP <- mean(OSP_status >= 1.0)
cat("\nProbability population is within OSP:", round(prob_in_OSP * 100, 1), "%\n")

```


```{r abundance and pp}

# 1. Combine the MCMC chains into a single matrix
# (Assuming 'out' is your mcmc.list object from runMCMC)
posterior_matrix <- do.call(rbind, out)

# 2. Extract the expected pups columns chronologically
n_occasions <- nim.constants$n_occasions
pup_cols <- paste0("expected_pups_tot[", 2:n_occasions, "]") # Starts at 2 because t+1 in the loop
pup_posterior <- posterior_matrix[, pup_cols]

# 3. Calculate the median and 95% Credible Intervals for each year
# We also append the actual census data here
pup_summary <- data.frame(
  TimeStep = 2:n_occasions, 
  Expected_Median = apply(pup_posterior, 2, median),
  Expected_LCI = apply(pup_posterior, 2, quantile, probs = 0.025),
  Expected_UCI = apply(pup_posterior, 2, quantile, probs = 0.975),
  Observed = nim.constants$y_pup_counts[2:n_occasions]
)

# 4. Plot the Posterior Predictive Check
ggplot(pup_summary, aes(x = TimeStep)) +
  # 95% Credible Interval Ribbon
  geom_ribbon(aes(ymin = Expected_LCI, ymax = Expected_UCI), 
              fill = "steelblue", alpha = 0.3) +
  # Median Expected Trend Line
  geom_line(aes(y = Expected_Median), color = "steelblue", size = 1) +
  # Actual Hard Census Data
  geom_point(aes(y = Observed), color = "black", size = 2) +
  theme_minimal() +
  labs(
    title = "Posterior Predictive Check: California Sea Lion Pup Production",
    subtitle = "Black dots = Census Data | Blue line & ribbon = Model Expected Pups (95% CI)",
    x = "Time Step",
    y = "Total Pups"
  ) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    axis.title = element_text(face = "bold")
  )


#### also plot scatterplot of int.phiP and beta.DD


```

```{r derive net productivity curve}

# 1. Extract your posterior medians
# (Replace 'posterior_matrix' with your actual combined MCMC output matrix)
# Baseline survival (converted to logit scale for the density penalty math)
mu_P_f <- qlogis(median(posterior_matrix[, "int.phiP"]))
mu_P_m <- qlogis(median(posterior_matrix[, "int.phiPM"]))

# Define a helper vector for female and male adult survival across indices 2 to 24
# You will need to map your specific age-class medians (int.phi1, int.phi2.3, etc.) 
# to the 23 transitions (Index 1 to 2, up to Index 24 to 25).
# For this example, I am using a simplified constant adult survival for brevity:
phi_adult_f <- rep(median(posterior_matrix[, "int.phiA"]), 24) 
phi_adult_m <- rep(median(posterior_matrix[, "int.phiAM"]), 24) 

# Fecundity and Density Dependence
fec_low <- median(posterior_matrix[, "int.fec_low"])
fec_high <- median(posterior_matrix[, "int.fec_high"])
beta_DD <- median(posterior_matrix[, "beta.DD"])

# 2. Setup the projection
n_years <- 300
N_f <- matrix(0, nrow = 25, ncol = n_years)
N_m <- matrix(0, nrow = 25, ncol = n_years)

# Seed a small founder population at t = 1
N_f[, 1] <- 100
N_m[, 1] <- 100

total_N <- numeric(n_years)
delta_N <- numeric(n_years)

total_N[1] <- sum(N_f[, 1]) + sum(N_m[, 1])

# 3. Project the population forward deterministically
for (t in 1:(n_years - 1)) {
  
  # Calculate density-dependent pup survival for this year
  # (SST is assumed to be 0 for an average environment)
  N_scaled <- total_N[t] / 100000
  phi_P_f_current <- plogis(mu_P_f - (beta_DD * N_scaled))
  phi_P_m_current <- plogis(mu_P_m - (beta_DD * N_scaled))
  
  # A. Transition the survivors first (Index 1 to 24 surviving to 2 to 25)
  N_f[2, t+1] <- N_f[1, t] * phi_P_f_current
  N_m[2, t+1] <- N_m[1, t] * phi_P_m_current
  
  for(a in 2:24) {
    N_f[a+1, t+1] <- N_f[a, t] * phi_adult_f[a]
    N_m[a+1, t+1] <- N_m[a, t] * phi_adult_m[a]
  }
  
  # B. Calculate post-breeding reproduction based on the new adult pool
  pups_tot <- (sum(N_f[5:10, t+1]) * fec_low) + (sum(N_f[11:23, t+1]) * fec_high)
  
  # Assign pups to Index 1 (50:50 sex ratio)
  N_f[1, t+1] <- pups_tot / 2
  N_m[1, t+1] <- pups_tot / 2
  
  # C. Record population metrics
  total_N[t+1] <- sum(N_f[, t+1]) + sum(N_m[, t+1])
  delta_N[t] <- total_N[t+1] - total_N[t]
}

# The final delta_N is NA because we don't project to t+1 at the end
delta_N[n_years] <- 0 

# 4. Find K and MNPL
# K is the maximum population size reached (where delta_N hits 0)
K_est <- max(total_N)
# MNPL is the population size where growth (delta_N) is maximized
MNPL_est <- total_N[which.max(delta_N)]

# 5. Plot the Net Productivity Curve
prod_data <- data.frame(N = total_N, Growth = delta_N) %>%
  filter(Growth > 0) # Remove the zero-growth equilibrium tail for a cleaner plot

ggplot(prod_data, aes(x = N, y = Growth)) +
  geom_line(color = "darkgreen", size = 1.2) +
  
  # Vertical line for MNPL
  geom_vline(xintercept = MNPL_est, linetype = "dashed", color = "blue") +
  annotate("text", x = MNPL_est, y = max(prod_data$Growth) * 0.9, 
           label = paste("MNPL =", round(MNPL_est)), color = "blue", hjust = -0.1) +
  
  # Vertical line for K
  geom_vline(xintercept = K_est, linetype = "dashed", color = "red") +
  annotate("text", x = K_est, y = max(prod_data$Growth) * 0.5, 
           label = paste("K =", round(K_est)), color = "red", hjust = 1.1) +
  
  theme_minimal() +
  labs(
    title = "Emergent Net Productivity Curve",
    x = "Total Population Size (N)",
    y = "Net Annual Growth (\u0394 N)"
  ) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    axis.title = element_text(face = "bold")
  )

# the curve shouldn't be a perfectly symmetrical parabola. It should rise steadily, peak (the blue MNPL line) noticeably to the right of the halfway mark ($0.5K$), and then crash steeply down to zero at carrying capacity (the red $K$ line). That right-skew is the biological signature of delayed density dependence acting exclusively on pup survival.

```


```{r temporal variance}

phi.vals <- post_sum %>%
  filter(grepl('.prob', variable)) %>%
    transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+)\\].*$', '\\1',
                                                variable)))) %>%
  #use when dataframe for phi.prob rather than vector
  # transform(year = as.numeric(as.character(gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\2', 
  #                                               variable)))) %>% 
  # transform(region = gsub('.+\\[([0-9]+), ([0-9]+)\\].*$', '\\1', variable)) %>%
  transform(variable = sub("\\[.*", "", variable)) %>%
  transform(rate = ifelse(grepl('phi', variable), 'Survival', 'Detection')) %>%
  transform(age = gsub('.prob', '', variable)) %>%
  transform(age = ifelse(rate == 'Survival', gsub('phi', '', age), 
                         ifelse(rate == 'Detection', gsub('p', '', age), NA))) %>%
  transform(sex = ifelse(grepl('M', age), 'Male', 'Female')) %>%
  transform(age = gsub('M', '', age)) %>%
  transform(age = factor(age, levels = c('P', '1', '2.3', '4.6', '7.9', '10.12', '13.16', '7.12', 'A'))) %>%
  # merge(mean.phi.vals %>% filter(site == 'Pyramid Rock'), by = c('age'), suffixes = c('', '.mean'))
  transform(exclude_det = ifelse(age == '2.3' & year < 2, 'Y',
                                   ifelse(age == '4.6' & year < 4, 'Y',
                                    ifelse(age == '7.12' & year < 7, 'Y',
                                           ifelse(age == 'A' & year < 13, 'Y', 'N'))))) %>%
  transform(exclude_phi = ifelse(age == '1' & year < 2, 'Y',
                             ifelse(age == '2.3' & year < 3, 'Y',
                                   ifelse(age == '4.6' & year < 5, 'Y',
                                    ifelse(age == '7.9' & year < 7, 'Y',
                                           ifelse(age == '10.12' & year < 10, 'Y',
                                                  ifelse(age == '13.16' & year < 13, 'Y',
                                           ifelse(age == 'A' & year < 16, 'Y', 'N'))))))))

#temporal variance with mean rates; intercept represents female, so can't show males
ggplot(phi.vals %>% filter(rate == 'Detection' & exclude_det != 'Y' & year != 20),
       aes(year, med)) +
  geom_errorbar(aes(x = year, ymin=lower, ymax=upper), position = position_dodge(0.5),
                width = 0.5, show.legend = F) +
  geom_point(size = 0.8, position = position_dodge(0.5)) +
  geom_line(linewidth = 0.7, position = position_dodge(0.5)) +
  # geom_line(aes(year, med.mean), col = 'grey20', linetype = 'dotted') +
  xlab('') + ylab(expression(paste('Detection probability ',  '(', p, ')'))) +
  ggtitle('') +
    facet_grid(age ~ sex) +
  plot_theme(legend.position = 'top', panel.border = element_rect(fill = NA),
             plot.title = element_text(hjust = 0.5)) +
  guides(color = guide_legend("", nrow = 1, byrow = T)) +
  scale_color_manual(values = rainbow2[c(2,3,5,6,7,8)], name = '') +
  scale_x_continuous(breaks = c(seq(1, 35, by = 5)), 
                     labels = c(seq(1990, (1990+n_occasions-1), by = 5)))

#survival
ggplot(phi.vals %>% filter(rate == 'Survival' & exclude_phi != 'Y'),
       aes(year, med)) +
  geom_errorbar(aes(x = year, ymin=lower, ymax=upper), position = position_dodge(0.5),
                width = 0.5, show.legend = F) +
  geom_point(size = 0.8, position = position_dodge(0.5)) +
  geom_line(linewidth = 0.7, position = position_dodge(0.5)) +
  # geom_line(aes(year, med.mean), col = 'grey20', linetype = 'dotted') +
  xlab('') + ylab(expression(paste('Survival probability ',  '(', phi, ')'))) +
  ggtitle('') +
    facet_grid(age ~ sex) +
  plot_theme(legend.position = 'top', panel.border = element_rect(fill = NA),
             plot.title = element_text(hjust = 0.5)) +
  guides(color = guide_legend("", nrow = 1, byrow = T)) +
  scale_color_manual(values = rainbow2[c(2,3,5,6,7,8)], name = '') +
  scale_x_continuous(breaks = c(seq(1, 25, by = 5)), labels = c(seq(2000, (2000+n_occasions-1), by = 5)))

ggplot(phi.vals %>% filter(rate == 'Survival' & exclude_phi != 'Y' &
                             age %in% c('P', '1') & sex == 'Female'),
       aes(year, med)) +
  geom_errorbar(aes(x = year, ymin=lower, ymax=upper), position = position_dodge(0.5),
                width = 0.5, show.legend = F) +
  geom_point(size = 0.8, position = position_dodge(0.5)) +
  geom_line(linewidth = 0.7, position = position_dodge(0.5)) +
  # geom_line(aes(year, med.mean), col = 'grey20', linetype = 'dotted') +
  xlab('') + ylab(expression(paste('Survival probability ',  ' (', phi, ')'))) +
  ggtitle('') +
    facet_grid(age ~ sex) +
  # theme_classic() +
  pres_theme(legend.position = 'top', #panel.border = element_rect(fill = NA),
             plot.title = element_text(hjust = 0.5)) +
  guides(color = guide_legend("", nrow = 1, byrow = T)) +
  scale_color_manual(values = rainbow2[c(2,3,5,6,7,8)], name = '') +
  scale_x_continuous(breaks = c(seq(1, 25, by = 5)), labels = c(seq(2000, (2000+n_occasions-1), by = 5)))


```


